// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/activities" | "/ai-assistant" | "/analytics" | "/billing" | "/boq" | "/budget" | "/communication" | "/dashboard" | "/dashboard/execution" | "/documents" | "/equipment" | "/finance" | "/inbox" | "/inventory" | "/labour" | "/login" | "/materials" | "/notifications" | "/procurement" | "/projects" | "/projects/[id]" | "/projects/[id]/completion" | "/qc" | "/qc/templates" | "/reports" | "/rework" | "/safety-qc" | "/settings" | "/users" | "/vendors" | "/work-orders"
type AppRouteHandlerRoutes = "/api/ai/parse-quotation-pdf" | "/api/procurement/preview-pdf" | "/api/procurement/purchase-orders/[id]/pdf" | "/api/procurement/purchase-requisitions/[id]/pdf"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = "/api/ai/chat" | "/api/check-license" | "/api/procurement/grns/[id]/pdf" | "/api/procurement/material-requests/[id]/pdf" | "/api/procurement/purchase-bills/[id]/pdf" | "/api/procurement/purchase-orders/[id]/pdf" | "/api/procurement/purchase-requisitions/[id]/pdf" | "/api/procurement/rfqs/[id]/pdf" | "/api/qc/analyze" | "/api/send-message" | "/api/site-inspection" | "/api/transcribe" | "/api/users" | "/api/users/[id]" | "/supabase-api/[[...path]]"
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/activities": {}
  "/ai-assistant": {}
  "/analytics": {}
  "/api/ai/chat": {}
  "/api/ai/parse-quotation-pdf": {}
  "/api/check-license": {}
  "/api/procurement/grns/[id]/pdf": { "id": string; }
  "/api/procurement/material-requests/[id]/pdf": { "id": string; }
  "/api/procurement/preview-pdf": {}
  "/api/procurement/purchase-bills/[id]/pdf": { "id": string; }
  "/api/procurement/purchase-orders/[id]/pdf": { "id": string; }
  "/api/procurement/purchase-requisitions/[id]/pdf": { "id": string; }
  "/api/procurement/rfqs/[id]/pdf": { "id": string; }
  "/api/qc/analyze": {}
  "/api/send-message": {}
  "/api/site-inspection": {}
  "/api/transcribe": {}
  "/api/users": {}
  "/api/users/[id]": { "id": string; }
  "/billing": {}
  "/boq": {}
  "/budget": {}
  "/communication": {}
  "/dashboard": {}
  "/dashboard/execution": {}
  "/documents": {}
  "/equipment": {}
  "/finance": {}
  "/inbox": {}
  "/inventory": {}
  "/labour": {}
  "/login": {}
  "/materials": {}
  "/notifications": {}
  "/procurement": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/completion": { "id": string; }
  "/qc": {}
  "/qc/templates": {}
  "/reports": {}
  "/rework": {}
  "/safety-qc": {}
  "/settings": {}
  "/supabase-api/[[...path]]": { "path"?: string[]; }
  "/users": {}
  "/vendors": {}
  "/work-orders": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
