-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text NOT NULL UNIQUE,
  name text,
  role text,
  created_by uuid,
  updated_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  organization_id uuid,
  phone text,
  avatar_url text,
  designation text,
  department text,
  deleted_at timestamp with time zone,
  project_id uuid,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT profiles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT profiles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT profiles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL,
  code text,
  name text NOT NULL,
  client_name text,
  location text,
  description text,
  project_value numeric,
  budget_amount numeric,
  actual_spend_amount numeric,
  start_date timestamp with time zone,
  target_end_date timestamp with time zone,
  current_phase text,
  status text,
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  organization_id uuid,
  completed_at timestamp with time zone,
  bua_sqft numeric DEFAULT 615000,
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT projects_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id)
);
CREATE TABLE public.project_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  user_id uuid,
  project_role text,
  is_active boolean DEFAULT true,
  created_by uuid,
  updated_by uuid,
  CONSTRAINT project_members_pkey PRIMARY KEY (id),
  CONSTRAINT project_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT project_members_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT project_members_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  name text NOT NULL,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  progress numeric DEFAULT 0,
  dependencies text,
  is_critical_path boolean DEFAULT false,
  created_by uuid,
  updated_by uuid,
  activity_id uuid,
  work_order_id uuid,
  actual_start_date date,
  completed_at timestamp with time zone,
  deleted_at timestamp with time zone,
  description text,
  title text,
  assigned_to uuid,
  assigned_name text,
  due_date date,
  priority text DEFAULT 'MEDIUM'::text,
  status text DEFAULT 'TODO'::text,
  location_block text,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT tasks_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT tasks_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT tasks_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT tasks_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT tasks_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id)
);
CREATE TABLE public.material_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  type text NOT NULL,
  quantity numeric NOT NULL,
  date timestamp with time zone DEFAULT now(),
  cost numeric DEFAULT 0,
  reference_no text,
  created_by uuid,
  updated_by uuid,
  project_id uuid,
  site_id uuid,
  location_id uuid,
  activity_id uuid,
  grn_id uuid,
  issue_slip_id uuid,
  item_id uuid,
  CONSTRAINT material_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT material_transactions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_transactions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT material_transactions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_transactions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT material_transactions_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id),
  CONSTRAINT material_transactions_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT material_transactions_grn_id_fkey FOREIGN KEY (grn_id) REFERENCES public.goods_receipt_notes(id),
  CONSTRAINT material_transactions_issue_slip_id_fkey FOREIGN KEY (issue_slip_id) REFERENCES public.material_issue_slips(id),
  CONSTRAINT material_transactions_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  sender_id uuid,
  body text,
  attachments ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  conversation_id uuid,
  type text DEFAULT 'text'::text,
  sender_email text,
  sender_name text,
  sender_role text,
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT messages_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT messages_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.daily_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  site_id uuid,
  dpr_id uuid,
  activity_id uuid,
  delay_id uuid,
  weather text,
  progress_delta numeric,
  site_limitations text,
  deleted_at timestamp with time zone,
  CONSTRAINT daily_logs_pkey PRIMARY KEY (id),
  CONSTRAINT daily_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT daily_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT daily_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT daily_logs_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT daily_logs_dpr_id_fkey FOREIGN KEY (dpr_id) REFERENCES public.daily_progress_reports(id),
  CONSTRAINT daily_logs_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT daily_logs_delay_id_fkey FOREIGN KEY (delay_id) REFERENCES public.delay_events(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  type text DEFAULT 'project_group'::text,
  title text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.conversation_members (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid,
  user_id uuid,
  project_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  last_read_at timestamp with time zone,
  CONSTRAINT conversation_members_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_members_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT conversation_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT conversation_members_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.message_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid,
  project_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  storage_path text,
  mime_type text,
  size_bytes bigint,
  duration_seconds integer,
  CONSTRAINT message_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT message_attachments_message_id_fkey FOREIGN KEY (message_id) REFERENCES public.messages(id),
  CONSTRAINT message_attachments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.organizations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  legal_name text,
  gst_number text,
  pan_number text,
  address text,
  phone text,
  email text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT organizations_pkey PRIMARY KEY (id),
  CONSTRAINT organizations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT organizations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.rbac_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  is_system boolean NOT NULL DEFAULT false,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT rbac_roles_pkey PRIMARY KEY (id),
  CONSTRAINT rbac_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT rbac_roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT rbac_roles_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.rbac_permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  module text NOT NULL,
  action text NOT NULL,
  description text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rbac_permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rbac_role_permissions (
  role_id uuid NOT NULL,
  permission_id uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT rbac_role_permissions_pkey PRIMARY KEY (role_id, permission_id),
  CONSTRAINT rbac_role_permissions_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.rbac_roles(id),
  CONSTRAINT rbac_role_permissions_permission_id_fkey FOREIGN KEY (permission_id) REFERENCES public.rbac_permissions(id),
  CONSTRAINT rbac_role_permissions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.rbac_user_roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  role_id uuid NOT NULL,
  project_id uuid,
  organization_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT rbac_user_roles_pkey PRIMARY KEY (id),
  CONSTRAINT rbac_user_roles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT rbac_user_roles_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.rbac_roles(id),
  CONSTRAINT rbac_user_roles_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT rbac_user_roles_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT rbac_user_roles_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name text NOT NULL,
  email text,
  role text,
  phone text,
  avatar_url text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES public.profiles(id)
);
CREATE TABLE public.audit_logs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  organization_id uuid,
  project_id uuid,
  actor_id uuid,
  action text NOT NULL,
  table_name text NOT NULL,
  record_id text NOT NULL,
  old_data jsonb,
  new_data jsonb,
  reason text,
  source USER-DEFINED NOT NULL DEFAULT 'dashboard'::erp_source_system,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT audit_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.entity_attachments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  entity_table text NOT NULL,
  entity_id uuid NOT NULL,
  document_type text,
  file_name text NOT NULL,
  storage_bucket text NOT NULL,
  storage_path text NOT NULL UNIQUE,
  mime_type text NOT NULL,
  size_bytes bigint CHECK (size_bytes IS NULL OR size_bytes > 0),
  document_hash text,
  is_required boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_document_status,
  uploaded_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT entity_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT entity_attachments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT entity_attachments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT entity_attachments_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id),
  CONSTRAINT entity_attachments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT entity_attachments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid,
  recipient_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  notification_type text NOT NULL,
  priority USER-DEFINED NOT NULL DEFAULT 'medium'::erp_priority,
  status USER-DEFINED NOT NULL DEFAULT 'queued'::erp_notification_status,
  entity_table text,
  entity_id uuid,
  action_url text,
  sent_at timestamp with time zone,
  read_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT notifications_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT notifications_recipient_id_fkey FOREIGN KEY (recipient_id) REFERENCES public.profiles(id),
  CONSTRAINT notifications_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT notifications_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.project_sites (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  project_id uuid NOT NULL,
  code text NOT NULL,
  name text NOT NULL,
  address text,
  site_manager_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT project_sites_pkey PRIMARY KEY (id),
  CONSTRAINT project_sites_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT project_sites_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_sites_site_manager_id_fkey FOREIGN KEY (site_manager_id) REFERENCES public.profiles(id),
  CONSTRAINT project_sites_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT project_sites_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.project_phases (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  name text NOT NULL,
  sequence_no integer NOT NULL CHECK (sequence_no > 0),
  planned_start_date date,
  planned_end_date date,
  actual_start_date date,
  actual_end_date date,
  status USER-DEFINED NOT NULL DEFAULT 'planned'::erp_activity_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT project_phases_pkey PRIMARY KEY (id),
  CONSTRAINT project_phases_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT project_phases_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT project_phases_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.cost_codes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  parent_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT cost_codes_pkey PRIMARY KEY (id),
  CONSTRAINT cost_codes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT cost_codes_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.cost_codes(id),
  CONSTRAINT cost_codes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT cost_codes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.budget_heads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  cost_code_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT budget_heads_pkey PRIMARY KEY (id),
  CONSTRAINT budget_heads_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_heads_cost_code_id_fkey FOREIGN KEY (cost_code_id) REFERENCES public.cost_codes(id),
  CONSTRAINT budget_heads_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_heads_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.budget_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  budget_head_id uuid NOT NULL,
  activity_id uuid,
  vendor_id uuid,
  allocation_name text NOT NULL,
  allocated_amount numeric NOT NULL DEFAULT 0 CHECK (allocated_amount >= 0::numeric),
  committed_amount numeric NOT NULL DEFAULT 0 CHECK (committed_amount >= 0::numeric),
  spent_amount numeric NOT NULL DEFAULT 0 CHECK (spent_amount >= 0::numeric),
  warning_threshold_percent numeric NOT NULL DEFAULT 80 CHECK (warning_threshold_percent >= 0::numeric AND warning_threshold_percent <= 100::numeric),
  hard_limit_percent numeric NOT NULL DEFAULT 100 CHECK (hard_limit_percent >= 0::numeric),
  status USER-DEFINED NOT NULL DEFAULT 'approved'::erp_workflow_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  category_id uuid,
  master_budget_item_id uuid,
  advance_amount numeric NOT NULL DEFAULT 0 CHECK (advance_amount >= 0::numeric),
  retention_held numeric NOT NULL DEFAULT 0 CHECK (retention_held >= 0::numeric),
  financial_year text,
  is_auto_provisioned boolean NOT NULL DEFAULT false,
  CONSTRAINT budget_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT budget_allocations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_allocations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT budget_allocations_budget_head_id_fkey FOREIGN KEY (budget_head_id) REFERENCES public.budget_heads(id),
  CONSTRAINT budget_allocations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_allocations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_allocations_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id),
  CONSTRAINT budget_allocations_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id),
  CONSTRAINT budget_allocations_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT budget_allocations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.budget_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  budget_allocation_id uuid NOT NULL,
  transaction_type USER-DEFINED NOT NULL,
  source_table text,
  source_id uuid,
  amount numeric NOT NULL CHECK (amount >= 0::numeric),
  description text,
  posted_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  financial_year text,
  category_id uuid,
  CONSTRAINT budget_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT budget_ledger_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_ledger_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT budget_ledger_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_ledger_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id)
);
CREATE TABLE public.budget_alerts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  budget_allocation_id uuid,
  alert_type text NOT NULL,
  threshold_percent numeric,
  actual_percent numeric,
  message text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_workflow_status,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  severity text NOT NULL DEFAULT 'warning'::text CHECK (severity = ANY (ARRAY['info'::text, 'warning'::text, 'critical'::text, 'overrun'::text])),
  CONSTRAINT budget_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT budget_alerts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_alerts_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT budget_alerts_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_alerts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_alerts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.boq_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  cost_code_id uuid,
  code text NOT NULL,
  description text NOT NULL,
  unit text NOT NULL,
  rate numeric NOT NULL CHECK (rate >= 0::numeric),
  estimated_qty numeric NOT NULL DEFAULT 0 CHECK (estimated_qty >= 0::numeric),
  consumed_qty numeric NOT NULL DEFAULT 0 CHECK (consumed_qty >= 0::numeric),
  approved boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT boq_items_pkey PRIMARY KEY (id),
  CONSTRAINT boq_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT boq_items_cost_code_id_fkey FOREIGN KEY (cost_code_id) REFERENCES public.cost_codes(id),
  CONSTRAINT boq_items_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT boq_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT boq_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.item_master (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  category_id uuid,
  uom_id uuid,
  sku text UNIQUE,
  name text NOT NULL,
  description text,
  specification text,
  default_rate numeric NOT NULL DEFAULT 0 CHECK (default_rate >= 0::numeric),
  gst_rate numeric NOT NULL DEFAULT 0 CHECK (gst_rate >= 0::numeric),
  min_stock_level numeric NOT NULL DEFAULT 0 CHECK (min_stock_level >= 0::numeric),
  is_stock_item boolean NOT NULL DEFAULT true,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT item_master_pkey PRIMARY KEY (id),
  CONSTRAINT item_master_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT item_master_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT item_master_category_id_refval_fkey FOREIGN KEY (category_id) REFERENCES public.reference_values(id),
  CONSTRAINT item_master_uom_id_refval_fkey FOREIGN KEY (uom_id) REFERENCES public.reference_values(id)
);
CREATE TABLE public.vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  vendor_code text UNIQUE,
  legal_name text NOT NULL,
  display_name text,
  gst_number text,
  pan_number text,
  email text,
  phone text,
  address text,
  compliance_status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_workflow_status,
  rating numeric NOT NULL DEFAULT 0 CHECK (rating >= 0::numeric AND rating <= 100::numeric),
  duplicate_key text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  location text,
  city text,
  pincode text,
  vendor_type text NOT NULL DEFAULT 'supplier'::text CHECK (vendor_type = ANY (ARRAY['supplier'::text, 'contractor'::text, 'both'::text])),
  contractor_code text,
  labour_category text,
  CONSTRAINT vendors_pkey PRIMARY KEY (id),
  CONSTRAINT vendors_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendors_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_contacts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_id uuid NOT NULL,
  name text NOT NULL,
  designation text,
  email text,
  phone text,
  is_primary boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT vendor_contacts_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_contacts_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_contacts_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_contacts_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.inventory_locations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  code text NOT NULL,
  name text NOT NULL,
  location_type text NOT NULL DEFAULT 'store'::text,
  manager_id uuid,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT inventory_locations_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_locations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT inventory_locations_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT inventory_locations_manager_id_fkey FOREIGN KEY (manager_id) REFERENCES public.profiles(id),
  CONSTRAINT inventory_locations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT inventory_locations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_balances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  location_id uuid,
  item_id uuid NOT NULL,
  available_qty numeric NOT NULL DEFAULT 0 CHECK (available_qty >= 0::numeric),
  reserved_qty numeric NOT NULL DEFAULT 0 CHECK (reserved_qty >= 0::numeric),
  consumed_qty numeric NOT NULL DEFAULT 0 CHECK (consumed_qty >= 0::numeric),
  rejected_qty numeric NOT NULL DEFAULT 0 CHECK (rejected_qty >= 0::numeric),
  average_rate numeric NOT NULL DEFAULT 0 CHECK (average_rate >= 0::numeric),
  stock_value numeric NOT NULL DEFAULT 0 CHECK (stock_value >= 0::numeric),
  reorder_level numeric NOT NULL DEFAULT 0 CHECK (reorder_level >= 0::numeric),
  last_transaction_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT stock_balances_pkey PRIMARY KEY (id),
  CONSTRAINT stock_balances_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT stock_balances_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT stock_balances_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id),
  CONSTRAINT stock_balances_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT stock_balances_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT stock_balances_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.stock_ledger (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  location_id uuid,
  item_id uuid NOT NULL,
  transaction_type USER-DEFINED NOT NULL,
  quantity numeric NOT NULL CHECK (quantity >= 0::numeric),
  rate numeric NOT NULL DEFAULT 0 CHECK (rate >= 0::numeric),
  amount numeric NOT NULL DEFAULT 0 CHECK (amount >= 0::numeric),
  source_table text,
  source_id uuid,
  source_line_id uuid,
  reference_no text,
  transaction_date date NOT NULL DEFAULT CURRENT_DATE,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  CONSTRAINT stock_ledger_pkey PRIMARY KEY (id),
  CONSTRAINT stock_ledger_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT stock_ledger_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT stock_ledger_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id),
  CONSTRAINT stock_ledger_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT stock_ledger_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.construction_activities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  phase_id uuid,
  boq_item_id uuid,
  cost_code_id uuid,
  parent_activity_id uuid,
  activity_code text,
  title text NOT NULL,
  description text,
  planned_start_date date,
  planned_end_date date,
  actual_start_date date,
  actual_end_date date,
  planned_qty numeric NOT NULL DEFAULT 0 CHECK (planned_qty >= 0::numeric),
  completed_qty numeric NOT NULL DEFAULT 0 CHECK (completed_qty >= 0::numeric),
  unit text,
  progress_percent integer NOT NULL DEFAULT 0 CHECK (progress_percent >= 0 AND progress_percent <= 100),
  priority USER-DEFINED NOT NULL DEFAULT 'medium'::erp_priority,
  status USER-DEFINED NOT NULL DEFAULT 'planned'::erp_activity_status,
  assigned_to uuid,
  is_critical_path boolean NOT NULL DEFAULT false,
  billing_allowed boolean NOT NULL DEFAULT false,
  deleted_reason text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT construction_activities_pkey PRIMARY KEY (id),
  CONSTRAINT construction_activities_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT construction_activities_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT construction_activities_phase_id_fkey FOREIGN KEY (phase_id) REFERENCES public.project_phases(id),
  CONSTRAINT construction_activities_boq_item_id_fkey FOREIGN KEY (boq_item_id) REFERENCES public.boq_items(id),
  CONSTRAINT construction_activities_cost_code_id_fkey FOREIGN KEY (cost_code_id) REFERENCES public.cost_codes(id),
  CONSTRAINT construction_activities_parent_activity_id_fkey FOREIGN KEY (parent_activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT construction_activities_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT construction_activities_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT construction_activities_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.daily_progress_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  report_no text NOT NULL,
  report_date date NOT NULL DEFAULT CURRENT_DATE,
  weather text,
  activities_planned text,
  activities_completed text,
  pending_activities text,
  delays text,
  delay_reason text,
  site_limitations text,
  engineer_remarks text,
  submitted_by uuid,
  submitted_at timestamp with time zone,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_workflow_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  photos jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT daily_progress_reports_pkey PRIMARY KEY (id),
  CONSTRAINT daily_progress_reports_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT daily_progress_reports_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT daily_progress_reports_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.dpr_activity_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  dpr_id uuid NOT NULL,
  project_id uuid NOT NULL,
  activity_id uuid,
  planned_work text,
  completed_work text,
  pending_work text,
  work_done_qty numeric NOT NULL DEFAULT 0 CHECK (work_done_qty >= 0::numeric),
  delay_minutes integer NOT NULL DEFAULT 0 CHECK (delay_minutes >= 0),
  delay_reason text,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  agency_name text,
  work_description text,
  no_of_persons integer DEFAULT 0,
  status text DEFAULT 'In Progress'::text,
  comments_issues text,
  agency_id uuid,
  contractor_name text,
  shift text DEFAULT 'Day'::text,
  location_zone text,
  work_type text,
  quantity_completed numeric DEFAULT 0.00,
  unit text DEFAULT 'sqft'::text,
  voice_note text DEFAULT ''::text,
  CONSTRAINT dpr_activity_lines_pkey PRIMARY KEY (id),
  CONSTRAINT dpr_activity_lines_dpr_id_fkey FOREIGN KEY (dpr_id) REFERENCES public.daily_progress_reports(id),
  CONSTRAINT dpr_activity_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT dpr_activity_lines_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT dpr_activity_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.delay_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  activity_id uuid,
  dpr_id uuid,
  planned_date date,
  actual_date date,
  delay_days integer NOT NULL DEFAULT 0 CHECK (delay_days >= 0),
  reason_code text NOT NULL,
  reason_details text,
  responsible_team text,
  responsible_user_id uuid,
  impact_on_timeline text,
  corrective_action text,
  status USER-DEFINED NOT NULL DEFAULT 'open'::erp_delay_status,
  resolved_at timestamp with time zone,
  resolved_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT delay_events_pkey PRIMARY KEY (id),
  CONSTRAINT delay_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT delay_events_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT delay_events_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT delay_events_dpr_id_fkey FOREIGN KEY (dpr_id) REFERENCES public.daily_progress_reports(id),
  CONSTRAINT delay_events_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES public.profiles(id),
  CONSTRAINT delay_events_resolved_by_fkey FOREIGN KEY (resolved_by) REFERENCES public.profiles(id),
  CONSTRAINT delay_events_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.checklists (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  activity_id uuid,
  title text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_qc_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT checklists_pkey PRIMARY KEY (id),
  CONSTRAINT checklists_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT checklists_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT checklists_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT checklists_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.checklist_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  checklist_id uuid NOT NULL,
  text text NOT NULL,
  done boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT checklist_items_pkey PRIMARY KEY (id),
  CONSTRAINT checklist_items_checklist_id_fkey FOREIGN KEY (checklist_id) REFERENCES public.checklists(id),
  CONSTRAINT checklist_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT checklist_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.material_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  activity_id uuid,
  mr_number text NOT NULL,
  source text NOT NULL DEFAULT 'onsite_requirement'::text,
  justification text,
  required_date date NOT NULL,
  priority USER-DEFINED NOT NULL DEFAULT 'medium'::erp_priority,
  stock_decision text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_procurement_status,
  raised_by uuid,
  submitted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  work_activity text,
  site_block text,
  clarification_text text,
  clarification_at timestamp with time zone,
  clarification_by uuid,
  clarification_reply text,
  clarification_replied_at timestamp with time zone,
  rejection_reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  management_comment text,
  management_comment_at timestamp with time zone,
  management_comment_by uuid,
  title text,
  company_name text,
  activity_code text,
  CONSTRAINT material_requests_pkey PRIMARY KEY (id),
  CONSTRAINT material_requests_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_requests_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT material_requests_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT material_requests_raised_by_fkey FOREIGN KEY (raised_by) REFERENCES public.profiles(id),
  CONSTRAINT material_requests_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_requests_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT material_requests_clarification_by_fkey FOREIGN KEY (clarification_by) REFERENCES public.profiles(id),
  CONSTRAINT material_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id),
  CONSTRAINT material_requests_management_comment_by_fkey FOREIGN KEY (management_comment_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.material_request_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  material_request_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_id uuid,
  item_description text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  uom_id uuid,
  estimated_rate numeric NOT NULL DEFAULT 0 CHECK (estimated_rate >= 0::numeric),
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  item_code text,
  item_group text,
  specification text,
  line_status text DEFAULT 'pending'::text,
  line_rejection_reason text,
  unit text DEFAULT 'nos'::text,
  converted_qty numeric NOT NULL DEFAULT 0,
  line_number integer,
  pending_pr_qty numeric DEFAULT GREATEST((quantity - COALESCE(converted_qty, (0)::numeric)), (0)::numeric),
  CONSTRAINT material_request_lines_pkey PRIMARY KEY (id),
  CONSTRAINT material_request_lines_material_request_id_fkey FOREIGN KEY (material_request_id) REFERENCES public.material_requests(id),
  CONSTRAINT material_request_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_request_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT material_request_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_request_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT material_request_lines_uom_id_refval_fkey FOREIGN KEY (uom_id) REFERENCES public.reference_values(id)
);
CREATE TABLE public.purchase_requisitions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  material_request_id uuid,
  budget_allocation_id uuid,
  pr_number text NOT NULL,
  title text NOT NULL,
  estimated_cost numeric NOT NULL DEFAULT 0 CHECK (estimated_cost >= 0::numeric),
  finance_required boolean NOT NULL DEFAULT false,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_procurement_status,
  current_approval_stage text,
  requested_date date NOT NULL DEFAULT CURRENT_DATE,
  required_date date,
  assigned_team_notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  company_name text,
  department text,
  pr_type text DEFAULT 'material'::text,
  priority text DEFAULT 'normal'::text,
  contractor_name text,
  contract_reference text,
  activity_name text,
  wbs_code text,
  delivery_address text,
  site_contact_person text,
  site_contact_number text,
  general_remarks text,
  total_amount numeric DEFAULT 0,
  pr_release_date date,
  budget_applicable boolean NOT NULL DEFAULT true,
  budget_head_id uuid,
  cost_code_id uuid,
  cost_centre text,
  activity_code text,
  over_budget_justification text,
  budget_status text,
  contractor_applicable boolean NOT NULL DEFAULT false,
  vendor_code text,
  scope_of_service text,
  contact_person text,
  contact_number text,
  delivery_instructions text,
  internal_notes text,
  terms_and_conditions text,
  prepared_by uuid,
  prepared_on timestamp with time zone,
  subtotal_amount numeric NOT NULL DEFAULT 0,
  service_subtotal numeric NOT NULL DEFAULT 0,
  discount_amount numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  freight_amount numeric NOT NULL DEFAULT 0,
  other_charges numeric NOT NULL DEFAULT 0,
  contingency_amount numeric NOT NULL DEFAULT 0,
  status_changed_at timestamp with time zone,
  assigned_to uuid,
  approved_by uuid,
  approved_at timestamp with time zone,
  cancellation_reason text,
  revision_number integer NOT NULL DEFAULT 0,
  revision_reason text,
  original_pr_id uuid,
  is_current_revision boolean NOT NULL DEFAULT true,
  master_budget_item_id uuid,
  CONSTRAINT purchase_requisitions_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_requisitions_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id),
  CONSTRAINT purchase_requisitions_prepared_by_fkey FOREIGN KEY (prepared_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisitions_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisitions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT purchase_requisitions_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT purchase_requisitions_material_request_id_fkey FOREIGN KEY (material_request_id) REFERENCES public.material_requests(id),
  CONSTRAINT purchase_requisitions_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT purchase_requisitions_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisitions_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisitions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT pr_budget_head_fk FOREIGN KEY (budget_head_id) REFERENCES public.budget_heads(id),
  CONSTRAINT pr_cost_code_fk FOREIGN KEY (cost_code_id) REFERENCES public.cost_codes(id)
);
CREATE TABLE public.purchase_requisition_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_requisition_id uuid NOT NULL,
  project_id uuid NOT NULL,
  material_request_line_id uuid,
  item_id uuid,
  item_description text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  uom_id uuid,
  estimated_rate numeric NOT NULL DEFAULT 0 CHECK (estimated_rate >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  resource_type text DEFAULT 'material'::text,
  item_code text,
  item_group text,
  specification text,
  preferred_brand text,
  suggested_vendor text,
  delivery_location text,
  remarks text,
  est_qty numeric,
  ind_qty numeric,
  iss_qty numeric,
  pr_bal_qty numeric,
  lead_period_days integer,
  lead_period_date date,
  project_stock numeric,
  line_number integer,
  tax_rate numeric DEFAULT 0,
  tax_amount numeric DEFAULT 0,
  line_total numeric DEFAULT 0,
  source_mr_id uuid,
  source_mr_number text,
  mr_line_number integer,
  approved_mr_qty numeric,
  prev_pr_qty numeric NOT NULL DEFAULT 0,
  remaining_mr_qty numeric,
  unit text DEFAULT 'nos'::text,
  required_date date,
  is_non_mr_item boolean NOT NULL DEFAULT false,
  non_mr_justification text,
  is_modified boolean NOT NULL DEFAULT false,
  removal_reason text,
  priority text,
  stock_audit text,
  project_and_block text,
  work_activity text,
  raised_by text,
  submitted_at timestamp with time zone,
  CONSTRAINT purchase_requisition_lines_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_requisition_lines_purchase_requisition_id_fkey FOREIGN KEY (purchase_requisition_id) REFERENCES public.purchase_requisitions(id),
  CONSTRAINT purchase_requisition_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT purchase_requisition_lines_material_request_line_id_fkey FOREIGN KEY (material_request_line_id) REFERENCES public.material_request_lines(id),
  CONSTRAINT purchase_requisition_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT purchase_requisition_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisition_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_requisition_lines_source_mr_id_fkey FOREIGN KEY (source_mr_id) REFERENCES public.material_requests(id),
  CONSTRAINT purchase_requisition_lines_uom_id_refval_fkey FOREIGN KEY (uom_id) REFERENCES public.reference_values(id)
);
CREATE TABLE public.rfqs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  purchase_requisition_id uuid NOT NULL,
  rfq_number text NOT NULL,
  title text NOT NULL,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  due_date date,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_procurement_status,
  terms text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT rfqs_pkey PRIMARY KEY (id),
  CONSTRAINT rfqs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT rfqs_purchase_requisition_id_fkey FOREIGN KEY (purchase_requisition_id) REFERENCES public.purchase_requisitions(id),
  CONSTRAINT rfqs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT rfqs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.rfq_vendors (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  rfq_id uuid NOT NULL,
  project_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  sent_at timestamp with time zone,
  response_status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_workflow_status,
  responded_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT rfq_vendors_pkey PRIMARY KEY (id),
  CONSTRAINT rfq_vendors_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES public.rfqs(id),
  CONSTRAINT rfq_vendors_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT rfq_vendors_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT rfq_vendors_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT rfq_vendors_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_quotations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  rfq_id uuid NOT NULL,
  vendor_id uuid NOT NULL,
  quotation_number text,
  quotation_date date NOT NULL DEFAULT CURRENT_DATE,
  subtotal_amount numeric NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  lead_time_days integer CHECK (lead_time_days IS NULL OR lead_time_days >= 0),
  delivery_terms text,
  payment_terms text,
  gst_details text,
  status USER-DEFINED NOT NULL DEFAULT 'submitted'::erp_workflow_status,
  storage_bucket text,
  storage_path text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  score_price numeric,
  score_delivery numeric,
  score_quality numeric,
  score_total numeric,
  score_remarks text,
  CONSTRAINT vendor_quotations_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_quotations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT vendor_quotations_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES public.rfqs(id),
  CONSTRAINT vendor_quotations_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_quotations_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_quotations_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.quotation_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  quotation_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_id uuid,
  item_description text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  uom_id uuid,
  unit_rate numeric NOT NULL CHECK (unit_rate >= 0::numeric),
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric),
  line_total numeric NOT NULL CHECK (line_total >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT quotation_lines_pkey PRIMARY KEY (id),
  CONSTRAINT quotation_lines_quotation_id_fkey FOREIGN KEY (quotation_id) REFERENCES public.vendor_quotations(id),
  CONSTRAINT quotation_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT quotation_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT quotation_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT quotation_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT quotation_lines_uom_id_refval_fkey FOREIGN KEY (uom_id) REFERENCES public.reference_values(id)
);
CREATE TABLE public.vendor_selections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  purchase_requisition_id uuid NOT NULL,
  rfq_id uuid,
  selected_quotation_id uuid NOT NULL,
  selected_vendor_id uuid NOT NULL,
  final_amount numeric NOT NULL DEFAULT 0 CHECK (final_amount >= 0::numeric),
  reason_for_selection text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_workflow_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT vendor_selections_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_selections_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT vendor_selections_purchase_requisition_id_fkey FOREIGN KEY (purchase_requisition_id) REFERENCES public.purchase_requisitions(id),
  CONSTRAINT vendor_selections_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES public.rfqs(id),
  CONSTRAINT vendor_selections_selected_quotation_id_fkey FOREIGN KEY (selected_quotation_id) REFERENCES public.vendor_quotations(id),
  CONSTRAINT vendor_selections_selected_vendor_id_fkey FOREIGN KEY (selected_vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_selections_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_selections_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_selections_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.purchase_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  vendor_id uuid NOT NULL,
  purchase_requisition_id uuid,
  vendor_selection_id uuid,
  budget_allocation_id uuid,
  po_number text NOT NULL,
  po_date date NOT NULL DEFAULT CURRENT_DATE,
  delivery_location text,
  delivery_date date,
  payment_terms text,
  terms_and_conditions text,
  subtotal_amount numeric NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  template_code text,
  pdf_storage_path text,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_po_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  sent_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  company_name text,
  contractor_name text,
  contract_reference text,
  site_contact_person text,
  site_contact_number text,
  terms_and_conditions_legal text,
  gst_194q_clause text,
  rera_warranty_clause text,
  master_budget_item_id uuid,
  CONSTRAINT purchase_orders_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_orders_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id),
  CONSTRAINT purchase_orders_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT purchase_orders_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT purchase_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT purchase_orders_purchase_requisition_id_fkey FOREIGN KEY (purchase_requisition_id) REFERENCES public.purchase_requisitions(id),
  CONSTRAINT purchase_orders_vendor_selection_id_fkey FOREIGN KEY (vendor_selection_id) REFERENCES public.vendor_selections(id),
  CONSTRAINT purchase_orders_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT purchase_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_orders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.purchase_order_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  purchase_order_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_id uuid,
  item_description text NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  uom_id uuid,
  unit_rate numeric NOT NULL CHECK (unit_rate >= 0::numeric),
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric),
  line_total numeric NOT NULL CHECK (line_total >= 0::numeric),
  received_qty numeric NOT NULL DEFAULT 0 CHECK (received_qty >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT purchase_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT purchase_order_lines_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT purchase_order_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT purchase_order_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT purchase_order_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_order_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT purchase_order_lines_uom_id_refval_fkey FOREIGN KEY (uom_id) REFERENCES public.reference_values(id)
);
CREATE TABLE public.goods_receipt_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  purchase_order_id uuid,
  vendor_id uuid,
  grn_number text NOT NULL,
  receipt_date date NOT NULL DEFAULT CURRENT_DATE,
  received_by uuid,
  quantity_verification text,
  physical_inspection text,
  damage_check text,
  quality_decision USER-DEFINED NOT NULL DEFAULT 'pending'::erp_qc_status,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_grn_status,
  posted_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  vehicle_no text,
  volume_in_brass text,
  net_weight text,
  in_weight text,
  out_weight text,
  challan_no text,
  challan_date date,
  transporter_name text,
  godown_name text,
  dealer_name text,
  qc_no text,
  remarks text,
  account_posting_amount numeric,
  asset_amount numeric DEFAULT 0,
  asset_item text,
  pb_lines_created numeric,
  unlocked_fy numeric DEFAULT 1.00,
  CONSTRAINT goods_receipt_notes_pkey PRIMARY KEY (id),
  CONSTRAINT goods_receipt_notes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT goods_receipt_notes_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT goods_receipt_notes_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT goods_receipt_notes_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT goods_receipt_notes_received_by_fkey FOREIGN KEY (received_by) REFERENCES public.profiles(id),
  CONSTRAINT goods_receipt_notes_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT goods_receipt_notes_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.goods_receipt_note_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  grn_id uuid NOT NULL,
  project_id uuid NOT NULL,
  purchase_order_line_id uuid,
  item_id uuid NOT NULL,
  received_qty numeric NOT NULL DEFAULT 0 CHECK (received_qty >= 0::numeric),
  accepted_qty numeric NOT NULL DEFAULT 0 CHECK (accepted_qty >= 0::numeric),
  rejected_qty numeric NOT NULL DEFAULT 0 CHECK (rejected_qty >= 0::numeric),
  unit_rate numeric NOT NULL DEFAULT 0 CHECK (unit_rate >= 0::numeric),
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  po_number text,
  pr_number text,
  item_group text,
  item_code text,
  item_brand text,
  item_description text,
  location text,
  purchase_category text,
  unit text,
  approved_qty numeric,
  po_balance_qty numeric,
  return_qty numeric,
  challan_qty numeric,
  balance_allowed numeric,
  current_balance_qty numeric,
  test_report_no text,
  expiry_date date,
  CONSTRAINT goods_receipt_note_lines_pkey PRIMARY KEY (id),
  CONSTRAINT goods_receipt_note_lines_grn_id_fkey FOREIGN KEY (grn_id) REFERENCES public.goods_receipt_notes(id),
  CONSTRAINT goods_receipt_note_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT goods_receipt_note_lines_purchase_order_line_id_fkey FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id),
  CONSTRAINT goods_receipt_note_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT goods_receipt_note_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT goods_receipt_note_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.material_issue_slips (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  location_id uuid,
  activity_id uuid,
  issue_number text NOT NULL,
  issued_to text NOT NULL,
  activity_team text,
  issue_date date NOT NULL DEFAULT CURRENT_DATE,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_workflow_status,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT material_issue_slips_pkey PRIMARY KEY (id),
  CONSTRAINT material_issue_slips_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_issue_slips_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT material_issue_slips_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.inventory_locations(id),
  CONSTRAINT material_issue_slips_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT material_issue_slips_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_issue_slips_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.material_issue_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  issue_slip_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_id uuid NOT NULL,
  quantity numeric NOT NULL CHECK (quantity > 0::numeric),
  rate numeric NOT NULL DEFAULT 0 CHECK (rate >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT material_issue_lines_pkey PRIMARY KEY (id),
  CONSTRAINT material_issue_lines_issue_slip_id_fkey FOREIGN KEY (issue_slip_id) REFERENCES public.material_issue_slips(id),
  CONSTRAINT material_issue_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT material_issue_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT material_issue_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT material_issue_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.work_orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  vendor_id uuid,
  contractor_id uuid,
  budget_allocation_id uuid,
  work_order_number text NOT NULL,
  scope_of_work text NOT NULL,
  start_date date,
  end_date date,
  terms_and_conditions text,
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_workflow_status,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT work_orders_pkey PRIMARY KEY (id),
  CONSTRAINT work_orders_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT work_orders_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT work_orders_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT work_orders_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT work_orders_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT work_orders_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT work_orders_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT work_orders_contractor_vendor_fkey FOREIGN KEY (contractor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.work_order_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  work_order_id uuid NOT NULL,
  project_id uuid NOT NULL,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 0 CHECK (quantity >= 0::numeric),
  unit text,
  rate numeric NOT NULL DEFAULT 0 CHECK (rate >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT work_order_lines_pkey PRIMARY KEY (id),
  CONSTRAINT work_order_lines_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id),
  CONSTRAINT work_order_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT work_order_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT work_order_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.labour_attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  contractor_id uuid,
  attendance_date date NOT NULL,
  present_count integer NOT NULL DEFAULT 0 CHECK (present_count >= 0),
  absent_count integer NOT NULL DEFAULT 0 CHECK (absent_count >= 0),
  overtime_hours numeric NOT NULL DEFAULT 0 CHECK (overtime_hours >= 0::numeric),
  productivity_percent numeric NOT NULL DEFAULT 100 CHECK (productivity_percent >= 0::numeric AND productivity_percent <= 200::numeric),
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT labour_attendance_pkey PRIMARY KEY (id),
  CONSTRAINT labour_attendance_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT labour_attendance_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT labour_attendance_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT labour_attendance_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT labour_attendance_contractor_vendor_fkey FOREIGN KEY (contractor_id) REFERENCES public.vendors(id)
);
CREATE TABLE public.equipment_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  site_id uuid,
  asset_code text UNIQUE,
  name text NOT NULL,
  equipment_type text,
  owner_vendor_id uuid,
  status USER-DEFINED NOT NULL DEFAULT 'active'::erp_equipment_status,
  total_usage_hours numeric NOT NULL DEFAULT 0 CHECK (total_usage_hours >= 0::numeric),
  total_fuel_consumed numeric NOT NULL DEFAULT 0 CHECK (total_fuel_consumed >= 0::numeric),
  last_maintenance_date date,
  next_maintenance_date date,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT equipment_assets_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_assets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT equipment_assets_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT equipment_assets_owner_vendor_id_fkey FOREIGN KEY (owner_vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT equipment_assets_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT equipment_assets_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.equipment_usage_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  equipment_id uuid NOT NULL,
  usage_date date NOT NULL DEFAULT CURRENT_DATE,
  usage_hours numeric NOT NULL DEFAULT 0 CHECK (usage_hours >= 0::numeric),
  fuel_consumed numeric NOT NULL DEFAULT 0 CHECK (fuel_consumed >= 0::numeric),
  activity_id uuid,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT equipment_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT equipment_usage_logs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT equipment_usage_logs_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment_assets(id),
  CONSTRAINT equipment_usage_logs_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT equipment_usage_logs_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT equipment_usage_logs_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.qc_checklist_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  category text NOT NULL,
  version text NOT NULL DEFAULT '1.0.0'::text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT qc_checklist_templates_pkey PRIMARY KEY (id),
  CONSTRAINT qc_checklist_templates_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES public.organizations(id),
  CONSTRAINT qc_checklist_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT qc_checklist_templates_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.qc_checklist_template_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  sequence_no integer NOT NULL CHECK (sequence_no > 0),
  description text NOT NULL,
  acceptance_criteria text,
  is_mandatory boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT qc_checklist_template_items_pkey PRIMARY KEY (id),
  CONSTRAINT qc_checklist_template_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.qc_checklist_templates(id),
  CONSTRAINT qc_checklist_template_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT qc_checklist_template_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.qc_inspections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  activity_id uuid,
  grn_id uuid,
  template_id uuid,
  inspection_number text NOT NULL,
  inspection_date date NOT NULL DEFAULT CURRENT_DATE,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_qc_status,
  remarks text,
  rework_required boolean NOT NULL DEFAULT false,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  CONSTRAINT qc_inspections_pkey PRIMARY KEY (id),
  CONSTRAINT qc_inspections_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT qc_inspections_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT qc_inspections_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT qc_inspections_grn_id_fkey FOREIGN KEY (grn_id) REFERENCES public.goods_receipt_notes(id),
  CONSTRAINT qc_inspections_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.qc_checklist_templates(id),
  CONSTRAINT qc_inspections_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT qc_inspections_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT qc_inspections_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.qc_inspection_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inspection_id uuid NOT NULL,
  project_id uuid NOT NULL,
  template_item_id uuid,
  description text NOT NULL,
  result USER-DEFINED NOT NULL DEFAULT 'pending'::erp_qc_status,
  remarks text,
  image_required boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT qc_inspection_items_pkey PRIMARY KEY (id),
  CONSTRAINT qc_inspection_items_inspection_id_fkey FOREIGN KEY (inspection_id) REFERENCES public.qc_inspections(id),
  CONSTRAINT qc_inspection_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT qc_inspection_items_template_item_id_fkey FOREIGN KEY (template_item_id) REFERENCES public.qc_checklist_template_items(id),
  CONSTRAINT qc_inspection_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT qc_inspection_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_bills (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  site_id uuid,
  vendor_id uuid NOT NULL,
  purchase_order_id uuid,
  work_order_id uuid,
  grn_id uuid,
  activity_id uuid,
  qc_inspection_id uuid,
  budget_allocation_id uuid,
  bill_number text NOT NULL,
  bill_date date NOT NULL,
  bill_book_number text,
  subtotal_amount numeric NOT NULL DEFAULT 0 CHECK (subtotal_amount >= 0::numeric),
  tax_amount numeric NOT NULL DEFAULT 0 CHECK (tax_amount >= 0::numeric),
  total_amount numeric NOT NULL DEFAULT 0 CHECK (total_amount >= 0::numeric),
  duplicate_detected boolean NOT NULL DEFAULT false,
  required_documents_received boolean NOT NULL DEFAULT false,
  work_completion_verified boolean NOT NULL DEFAULT false,
  qc_approval_verified boolean NOT NULL DEFAULT false,
  payment_status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_payment_status,
  status USER-DEFINED NOT NULL DEFAULT 'draft'::erp_billing_status,
  verified_by uuid,
  verified_at timestamp with time zone,
  approved_by uuid,
  approved_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  deleted_at timestamp with time zone,
  po_value numeric,
  grn_value numeric,
  invoice_value numeric,
  tolerance_amount numeric DEFAULT 0,
  match_status text,
  match_remarks text,
  master_budget_item_id uuid,
  retention_percent numeric NOT NULL DEFAULT 0 CHECK (retention_percent >= 0::numeric AND retention_percent <= 100::numeric),
  retention_amount numeric NOT NULL DEFAULT 0 CHECK (retention_amount >= 0::numeric),
  advance_adjusted numeric NOT NULL DEFAULT 0 CHECK (advance_adjusted >= 0::numeric),
  other_deductions numeric NOT NULL DEFAULT 0 CHECK (other_deductions >= 0::numeric),
  net_payable_amount numeric NOT NULL DEFAULT 0,
  ledger_remarks text,
  CONSTRAINT vendor_bills_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bills_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id),
  CONSTRAINT vendor_bills_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT vendor_bills_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.project_sites(id),
  CONSTRAINT vendor_bills_vendor_id_fkey FOREIGN KEY (vendor_id) REFERENCES public.vendors(id),
  CONSTRAINT vendor_bills_purchase_order_id_fkey FOREIGN KEY (purchase_order_id) REFERENCES public.purchase_orders(id),
  CONSTRAINT vendor_bills_work_order_id_fkey FOREIGN KEY (work_order_id) REFERENCES public.work_orders(id),
  CONSTRAINT vendor_bills_grn_id_fkey FOREIGN KEY (grn_id) REFERENCES public.goods_receipt_notes(id),
  CONSTRAINT vendor_bills_activity_id_fkey FOREIGN KEY (activity_id) REFERENCES public.construction_activities(id),
  CONSTRAINT vendor_bills_qc_inspection_id_fkey FOREIGN KEY (qc_inspection_id) REFERENCES public.qc_inspections(id),
  CONSTRAINT vendor_bills_budget_allocation_id_fkey FOREIGN KEY (budget_allocation_id) REFERENCES public.budget_allocations(id),
  CONSTRAINT vendor_bills_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_bills_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_bills_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_bills_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.vendor_bill_lines (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  vendor_bill_id uuid NOT NULL,
  project_id uuid NOT NULL,
  item_id uuid,
  work_order_line_id uuid,
  purchase_order_line_id uuid,
  description text NOT NULL,
  quantity numeric NOT NULL DEFAULT 1 CHECK (quantity > 0::numeric),
  unit text,
  rate numeric NOT NULL DEFAULT 0 CHECK (rate >= 0::numeric),
  tax_rate numeric NOT NULL DEFAULT 0 CHECK (tax_rate >= 0::numeric),
  line_total numeric NOT NULL DEFAULT 0 CHECK (line_total >= 0::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT vendor_bill_lines_pkey PRIMARY KEY (id),
  CONSTRAINT vendor_bill_lines_vendor_bill_id_fkey FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id),
  CONSTRAINT vendor_bill_lines_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT vendor_bill_lines_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.item_master(id),
  CONSTRAINT vendor_bill_lines_work_order_line_id_fkey FOREIGN KEY (work_order_line_id) REFERENCES public.work_order_lines(id),
  CONSTRAINT vendor_bill_lines_purchase_order_line_id_fkey FOREIGN KEY (purchase_order_line_id) REFERENCES public.purchase_order_lines(id),
  CONSTRAINT vendor_bill_lines_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT vendor_bill_lines_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  vendor_bill_id uuid NOT NULL,
  payment_reference text NOT NULL,
  payment_date date,
  amount numeric NOT NULL CHECK (amount > 0::numeric),
  status USER-DEFINED NOT NULL DEFAULT 'pending'::erp_payment_status,
  payment_mode text,
  remarks text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT payments_vendor_bill_id_fkey FOREIGN KEY (vendor_bill_id) REFERENCES public.vendor_bills(id),
  CONSTRAINT payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT payments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.user_site_assignments (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  site_id uuid NOT NULL,
  assignment_role text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT user_site_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_site_assignments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT user_site_assignments_site_id_fkey FOREIGN KEY (site_id) REFERENCES public.projects(id),
  CONSTRAINT user_site_assignments_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT user_site_assignments_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.document_activity_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  entity_table text NOT NULL,
  entity_id uuid NOT NULL,
  action text NOT NULL,
  previous_status text,
  new_status text,
  actor_id uuid,
  actor_role text,
  comment text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT document_activity_log_pkey PRIMARY KEY (id),
  CONSTRAINT document_activity_log_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT document_activity_log_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.reference_values (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  kind text NOT NULL CHECK (kind = ANY (ARRAY['uom'::text, 'item_category'::text, 'vendor_category'::text])),
  code text NOT NULL,
  name text NOT NULL,
  parent_id uuid,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  CONSTRAINT reference_values_pkey PRIMARY KEY (id),
  CONSTRAINT reference_values_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.reference_values(id),
  CONSTRAINT reference_values_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT reference_values_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.site_agencies (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  agency_name text NOT NULL,
  trade_category text NOT NULL,
  contact_person text,
  phone text,
  assigned_zone text,
  active_workers_count integer DEFAULT 0,
  supervisor_name text,
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'inactive'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_agencies_pkey PRIMARY KEY (id),
  CONSTRAINT site_agencies_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.site_issues (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  issue_number text NOT NULL,
  title text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'work_stoppage'::text CHECK (category = ANY (ARRAY['work_stoppage'::text, 'logistics'::text, 'safety'::text, 'quality'::text, 'design'::text, 'material'::text])),
  severity text NOT NULL DEFAULT 'medium'::text CHECK (severity = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  location_zone text,
  stoppage_hours numeric DEFAULT 0.0,
  status text NOT NULL DEFAULT 'open'::text CHECK (status = ANY (ARRAY['open'::text, 'in_progress'::text, 'resolved'::text, 'closed'::text])),
  assigned_to uuid,
  assigned_to_name text,
  target_resolution_date date,
  resolution_remarks text,
  photo_urls jsonb DEFAULT '[]'::jsonb,
  created_by uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_issues_pkey PRIMARY KEY (id),
  CONSTRAINT site_issues_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT site_issues_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.profiles(id),
  CONSTRAINT site_issues_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.site_photos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  dpr_id uuid,
  photo_url text NOT NULL,
  title text NOT NULL,
  location_zone text,
  is_verified boolean DEFAULT true,
  uploaded_by uuid,
  uploaded_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT site_photos_pkey PRIMARY KEY (id),
  CONSTRAINT site_photos_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT site_photos_dpr_id_fkey FOREIGN KEY (dpr_id) REFERENCES public.daily_progress_reports(id),
  CONSTRAINT site_photos_uploaded_by_fkey FOREIGN KEY (uploaded_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.qc_templates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  title character varying NOT NULL,
  category character varying NOT NULL,
  description text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qc_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.qc_template_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid NOT NULL,
  sr_no integer NOT NULL,
  parameter_name text NOT NULL,
  stage USER-DEFINED DEFAULT 'general'::qc_stage_phase,
  has_site_dimension boolean DEFAULT false,
  default_specification text,
  is_required boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qc_template_items_pkey PRIMARY KEY (id),
  CONSTRAINT qc_template_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.qc_templates(id)
);
CREATE TABLE public.qc_non_conformities (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ncr_number character varying NOT NULL UNIQUE,
  inspection_id uuid,
  project_id uuid,
  problem_identification text NOT NULL,
  corrective_measures text,
  primary_responsibility character varying,
  secondary_responsibility character varying,
  target_date date,
  rectified_date date,
  status USER-DEFINED DEFAULT 'open'::qc_ncr_status,
  photo_urls jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qc_non_conformities_pkey PRIMARY KEY (id),
  CONSTRAINT qc_non_conformities_inspection_id_fkey FOREIGN KEY (inspection_id) REFERENCES public.qc_inspections(id),
  CONSTRAINT qc_non_conformities_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.qc_cube_tests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  inspection_id uuid,
  project_id uuid,
  tower character varying,
  activity character varying,
  slump_mm numeric,
  grade_of_concrete character varying NOT NULL,
  casting_date date NOT NULL,
  curing_start_date date,
  curing_finish_date date,
  testing_date date,
  cube_weight_kg numeric,
  force_7_days_kn numeric,
  strength_7_days_n_mm2 numeric,
  avg_strength_7_days_n_mm2 numeric,
  force_28_days_kn numeric,
  strength_28_days_n_mm2 numeric,
  avg_strength_28_days_n_mm2 numeric,
  pass_fail boolean,
  remarks text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT qc_cube_tests_pkey PRIMARY KEY (id),
  CONSTRAINT qc_cube_tests_inspection_id_fkey FOREIGN KEY (inspection_id) REFERENCES public.qc_inspections(id),
  CONSTRAINT qc_cube_tests_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.outbound_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  message_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT outbound_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.master_budget_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  budget_head_id uuid,
  category_name text,
  sr_no text NOT NULL,
  item_description text NOT NULL,
  qty_rcc numeric DEFAULT 0 CHECK (qty_rcc >= 0::numeric),
  qty_finishes numeric DEFAULT 0 CHECK (qty_finishes >= 0::numeric),
  qty_infra numeric DEFAULT 0 CHECK (qty_infra >= 0::numeric),
  qty_total numeric NOT NULL DEFAULT 0 CHECK (qty_total >= 0::numeric),
  unit text NOT NULL DEFAULT 'LS'::text,
  estimated_rate numeric NOT NULL DEFAULT 0 CHECK (estimated_rate >= 0::numeric),
  budgeted_cost numeric NOT NULL DEFAULT 0 CHECK (budgeted_cost >= 0::numeric),
  cost_per_bua numeric NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  version_number integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  created_by uuid,
  updated_by uuid,
  category_id uuid,
  scope_tag text DEFAULT 'site_infra'::text CHECK (scope_tag = ANY (ARRAY['building_rcc'::text, 'building_finishes'::text, 'site_infra'::text])),
  item_type text DEFAULT 'material'::text CHECK (item_type = ANY (ARRAY['material'::text, 'labour'::text, 'service'::text, 'equipment'::text, 'subcontract'::text, 'mixed'::text])),
  sort_order integer NOT NULL DEFAULT 0,
  deleted_at timestamp with time zone,
  CONSTRAINT master_budget_items_pkey PRIMARY KEY (id),
  CONSTRAINT master_budget_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT master_budget_items_budget_head_id_fkey FOREIGN KEY (budget_head_id) REFERENCES public.budget_heads(id),
  CONSTRAINT master_budget_items_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.profiles(id),
  CONSTRAINT master_budget_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT master_budget_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id)
);
CREATE TABLE public.budget_revisions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  version_number integer NOT NULL,
  version_label text NOT NULL,
  justification_reason text NOT NULL,
  old_total_cost numeric NOT NULL DEFAULT 0,
  new_total_cost numeric NOT NULL DEFAULT 0,
  net_diff_amount numeric NOT NULL DEFAULT 0,
  edited_by uuid,
  edited_by_name text NOT NULL DEFAULT 'Pramukh ERP User'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'approved'::text CHECK (status = ANY (ARRAY['draft'::text, 'submitted'::text, 'approved'::text, 'rejected'::text])),
  approved_by uuid,
  approved_at timestamp with time zone,
  scope text NOT NULL DEFAULT 'master_budget'::text CHECK (scope = ANY (ARRAY['master_budget'::text, 'variance_reconciliation'::text, 'excel_import'::text])),
  CONSTRAINT budget_revisions_pkey PRIMARY KEY (id),
  CONSTRAINT budget_revisions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_revisions_edited_by_fkey FOREIGN KEY (edited_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_revisions_approved_by_fkey FOREIGN KEY (approved_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.budget_revision_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  revision_id uuid NOT NULL,
  master_budget_item_id uuid,
  sub_activity text NOT NULL,
  category_name text NOT NULL,
  old_qty numeric NOT NULL,
  new_qty numeric NOT NULL,
  old_rate numeric NOT NULL,
  new_rate numeric NOT NULL,
  old_cost numeric NOT NULL,
  new_cost numeric NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT budget_revision_items_pkey PRIMARY KEY (id),
  CONSTRAINT budget_revision_items_revision_id_fkey FOREIGN KEY (revision_id) REFERENCES public.budget_revisions(id),
  CONSTRAINT budget_revision_items_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id)
);
CREATE TABLE public.budget_variance_items (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  master_budget_item_id uuid,
  sr_no text NOT NULL,
  sub_activity text NOT NULL,
  category_name text NOT NULL,
  unit text NOT NULL,
  work_status text DEFAULT 'In Progress'::text,
  budget_qty numeric NOT NULL DEFAULT 0,
  budget_rate numeric NOT NULL DEFAULT 0,
  budget_cost numeric NOT NULL DEFAULT 0,
  po_qty numeric DEFAULT 0,
  po_rate numeric DEFAULT 0,
  po_amount numeric DEFAULT 0,
  actual_bill_qty numeric NOT NULL DEFAULT 0,
  actual_bill_rate numeric NOT NULL DEFAULT 0,
  actual_total_cost numeric NOT NULL DEFAULT 0,
  qty_variation numeric NOT NULL DEFAULT 0,
  rate_variation numeric NOT NULL DEFAULT 0,
  balance_amount numeric NOT NULL DEFAULT 0,
  cost_variance_amount numeric NOT NULL DEFAULT 0,
  cost_variance_percent numeric NOT NULL DEFAULT 0,
  remark text,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  category_id uuid,
  CONSTRAINT budget_variance_items_pkey PRIMARY KEY (id),
  CONSTRAINT budget_variance_items_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_variance_items_master_budget_item_id_fkey FOREIGN KEY (master_budget_item_id) REFERENCES public.master_budget_items(id),
  CONSTRAINT budget_variance_items_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id),
  CONSTRAINT budget_variance_items_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.budget_categories(id)
);
CREATE TABLE public.budget_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid NOT NULL,
  category_name text NOT NULL,
  category_code text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  deleted_at timestamp with time zone,
  CONSTRAINT budget_categories_pkey PRIMARY KEY (id),
  CONSTRAINT budget_categories_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.budget_config (
  project_id uuid NOT NULL,
  caution_threshold_percent numeric NOT NULL DEFAULT 50,
  warning_threshold_percent numeric NOT NULL DEFAULT 75,
  critical_threshold_percent numeric NOT NULL DEFAULT 90,
  hard_limit_percent numeric NOT NULL DEFAULT 100,
  hard_limit_enforcement text NOT NULL DEFAULT 'block'::text CHECK (hard_limit_enforcement = ANY (ARRAY['block'::text, 'warn_only'::text])),
  require_justification_over_budget boolean NOT NULL DEFAULT true,
  current_fy text NOT NULL DEFAULT '2026-27'::text,
  budget_lock_enabled boolean NOT NULL DEFAULT false,
  default_retention_percent numeric NOT NULL DEFAULT 5 CHECK (default_retention_percent >= 0::numeric AND default_retention_percent <= 100::numeric),
  default_gst_percent numeric NOT NULL DEFAULT 18 CHECK (default_gst_percent >= 0::numeric AND default_gst_percent <= 100::numeric),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by uuid,
  CONSTRAINT budget_config_pkey PRIMARY KEY (project_id),
  CONSTRAINT budget_config_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT budget_config_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.profiles(id)
);