'use client';

import { useState } from 'react';
import {
  FileText,
  Eye,
  Download,
  CheckCircle2,
  Clock,
  Building2,
  X,
  ExternalLink,
  ShieldCheck,
  Smartphone,
  Printer,
} from 'lucide-react';
import type { GrnRow } from './grn-stats-bar';

interface GrnTableViewProps {
  grns: GrnRow[];
  onOpenGrnForm: (grn: GrnRow) => void;
  onStatusToggle?: (id: string, newStatus: 'site_engineer' | 'approved') => void;
}

export function GrnTableView({ grns, onOpenGrnForm, onStatusToggle }: GrnTableViewProps) {
  // Modal states for Challan PDF and GRN Report
  const [selectedChallanPdf, setSelectedChallanPdf] = useState<GrnRow | null>(null);
  const [selectedReport, setSelectedReport] = useState<GrnRow | null>(null);

  if (grns.length === 0) {
    return (
      <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center shadow-xs">
        <Smartphone className="mx-auto h-10 w-10 text-muted-foreground/40" />
        <p className="mt-3 text-sm font-semibold text-muted-foreground font-heading">
          No GRNs Submitted From Mobile App Yet
        </p>
        <p className="mt-1 text-xs text-muted-foreground/70 font-medium">
          When Site Engineers receive material on-site and submit GRNs via the Pramukh Mobile App, they will reflect here instantly.
        </p>
      </div>
    );
  }

  const handleDownloadPdf = (grn: GrnRow) => {
    // Generate dummy PDF file download
    const element = document.createElement('a');
    const file = new Blob([
      `PRAMUKH GROUP - DELIVERY CHALLAN ATTACHMENT\n=========================================\nGRN NO: ${grn.grn_number}\nPO REF: ${grn.po_number}\nCHALLAN NO: ${grn.challan_no}\nSUPPLIER: ${grn.vendor_name}\nPROJECT SITE: ${grn.project_name}\nGODOWN: ${grn.godown_name}\nRECEIVED DATE: ${grn.received_date}\nSITE ENGINEER LOGGED: ${grn.site_engineer_name || 'Divyesh Jasani'}\nSTATUS: ${grn.status === 'approved' ? 'HQ Approved' : 'Submitted by Site Engineer'}\n=========================================\nDOCUMENT AUDIT PASSED - PRAMUKH ERP`
    ], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `${grn.challan_pdf_name || `Delivery_Challan_${grn.challan_no}`}.pdf`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  const handleDownloadReport = (grn: GrnRow) => {
    const element = document.createElement('a');
    const file = new Blob([
      `PRAMUKH GROUP ERP - GOODS RECEIPT NOTE (GRN) OFFICIAL REPORT\n===========================================================\nGRN NO: ${grn.grn_number}\nGRN DATE: ${grn.received_date}\nPROJECT SITE: ${grn.project_name}\nSUPPLIER NAME: ${grn.vendor_name}\nGODOWN STORE: ${grn.godown_name}\nCHALLAN NO: ${grn.challan_no}\nFROM PO: ${grn.po_number}\nSUBMITTED BY: ${grn.site_engineer_name || 'Divyesh Jasani'} (Pramukh Site Mobile App)\nAPPROVAL STATUS: ${grn.status === 'approved' ? 'Approved (HQ Verified)' : 'Submitted by Site Engineer'}\n\nMATERIAL RECEIPT BREAKDOWN:\n- Hydropneumatics Pump Connection Line Assembly: 12 NOS\n- Account Posting Material Amount: ₹${grn.total_val.toLocaleString('en-IN')}\n- QC Inspection: PASSED & VERIFIED ON SITE\n===========================================================\nGenerated by Pramukh Group AI ERP V2`
    ], { type: 'text/plain' });
    element.href = URL.createObjectURL(file);
    element.download = `GRN_Report_${grn.grn_number.replace(/\//g, '_')}.pdf`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="space-y-3">
      {/* 12-Column Table Container */}
      <div className="overflow-hidden rounded-xl border border-border bg-card shadow-2xs">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs whitespace-nowrap">
            <thead>
              <tr className="border-b border-border bg-muted/60 font-heading text-[11px] font-bold uppercase tracking-wider text-muted-foreground">
                <th className="px-3 py-3.5 text-center w-12">SR</th>
                <th className="px-3.5 py-3.5 font-bold text-primary">G.R. NO.</th>
                <th className="px-3.5 py-3.5">GRN Date</th>
                <th className="px-3.5 py-3.5">Project Name</th>
                <th className="px-3.5 py-3.5">Supplier Name</th>
                <th className="px-3.5 py-3.5">Godown Name</th>
                <th className="px-3.5 py-3.5 font-mono">Challan No.</th>
                <th className="px-3.5 py-3.5 font-mono">From P.O.s</th>
                <th className="px-3.5 py-3.5 text-center">Status</th>
                <th className="px-3.5 py-3.5 text-center">Challan PDF</th>
                <th className="px-3.5 py-3.5 text-center">View Form</th>
                <th className="px-3.5 py-3.5 text-right">Download Form Report</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border/60">
              {grns.map((grn, index) => {
                const isApproved = grn.status === 'approved';

                return (
                  <tr key={grn.id} className="group hover:bg-muted/30 transition-colors align-middle font-sans">
                    {/* 1. SR */}
                    <td className="px-3 py-3 text-center font-mono font-bold text-muted-foreground">
                      {index + 1}
                    </td>

                    {/* 2. G.R. NO. */}
                    <td className="px-3.5 py-3">
                      <span className="font-mono font-extrabold text-primary text-xs">
                        {grn.grn_number}
                      </span>
                    </td>

                    {/* 3. GRN Date */}
                    <td className="px-3.5 py-3">
                      <span className="font-semibold text-foreground text-xs">
                        {grn.received_date}
                      </span>
                    </td>

                    {/* 4. Project Name */}
                    <td className="px-3.5 py-3">
                      <span className="font-bold text-foreground text-xs flex items-center gap-1.5">
                        <Building2 className="h-3.5 w-3.5 text-muted-foreground/70" />
                        {grn.project_name}
                      </span>
                    </td>

                    {/* 5. Supplier Name */}
                    <td className="px-3.5 py-3">
                      <span className="font-bold text-foreground text-xs truncate max-w-[200px] block">
                        {grn.vendor_name}
                      </span>
                    </td>

                    {/* 6. Godown Name */}
                    <td className="px-3.5 py-3">
                      <span className="font-semibold text-muted-foreground text-xs">
                        {grn.godown_name || 'Revanta C.O.P Store'}
                      </span>
                    </td>

                    {/* 7. Challan No. */}
                    <td className="px-3.5 py-3 font-mono font-bold text-foreground">
                      {grn.challan_no || '159'}
                    </td>

                    {/* 8. From P.O.s */}
                    <td className="px-3.5 py-3">
                      <span className="font-mono font-bold text-blue-600 dark:text-blue-400 text-xs">
                        {grn.po_number}
                      </span>
                    </td>

                    {/* 9. Status (Site Engineer or Approved) */}
                    <td className="px-3.5 py-3 text-center">
                      {isApproved ? (
                        <button
                          type="button"
                          onClick={() => onStatusToggle?.(grn.id, 'site_engineer')}
                          title="Click to revert to Site Engineer status"
                          className="inline-flex items-center gap-1.5 rounded-full border border-emerald-500/30 bg-emerald-500/15 px-2.5 py-1 text-[11px] font-extrabold text-emerald-700 dark:text-emerald-300 hover:bg-emerald-500/25 transition-colors cursor-pointer"
                        >
                          <CheckCircle2 className="h-3.5 w-3.5" /> Approved
                        </button>
                      ) : (
                        <button
                          type="button"
                          onClick={() => onStatusToggle?.(grn.id, 'approved')}
                          title="Click to verify & Approve GRN"
                          className="inline-flex items-center gap-1.5 rounded-full border border-amber-500/30 bg-amber-500/15 px-2.5 py-1 text-[11px] font-extrabold text-amber-700 dark:text-amber-300 hover:bg-amber-500/25 transition-colors cursor-pointer"
                        >
                          <Clock className="h-3.5 w-3.5" /> Submitted by Site Engineer
                        </button>
                      )}
                    </td>

                    {/* 10. Challan PDF download */}
                    <td className="px-3.5 py-3 text-center">
                      <div className="flex items-center justify-center gap-1">
                        <button
                          type="button"
                          onClick={() => setSelectedChallanPdf(grn)}
                          className="inline-flex items-center gap-1 rounded-lg border border-border bg-background px-2.5 py-1 text-[11px] font-bold text-foreground hover:bg-muted transition-colors shadow-2xs"
                        >
                          <Eye className="h-3.5 w-3.5 text-blue-500" /> Preview
                        </button>
                        <button
                          type="button"
                          onClick={() => handleDownloadPdf(grn)}
                          className="inline-flex items-center gap-1 rounded-lg border border-blue-500/30 bg-blue-500/10 px-2 py-1 text-[11px] font-bold text-blue-600 hover:bg-blue-500/20 transition-colors"
                          title="Download Challan PDF"
                        >
                          <Download className="h-3.5 w-3.5" /> PDF
                        </button>
                      </div>
                    </td>

                    {/* 11. View Form */}
                    <td className="px-3.5 py-3 text-center">
                      <button
                        type="button"
                        onClick={() => onOpenGrnForm(grn)}
                        className="inline-flex items-center gap-1.5 rounded-lg bg-primary px-3 py-1.5 text-xs font-bold text-primary-foreground hover:bg-primary/90 transition-all shadow-2xs"
                      >
                        <Eye className="h-3.5 w-3.5" /> View Form
                      </button>
                    </td>

                    {/* 12. Download Form Report */}
                    <td className="px-3.5 py-3 text-right">
                      <button
                        type="button"
                        onClick={() => handleDownloadReport(grn)}
                        className="inline-flex items-center gap-1.5 rounded-lg border border-emerald-600/30 bg-emerald-600/10 px-3 py-1.5 text-xs font-extrabold text-emerald-700 dark:text-emerald-300 hover:bg-emerald-600/20 transition-all"
                      >
                        <FileText className="h-3.5 w-3.5 text-emerald-600" /> Download Report
                      </button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>

      {/* ========================================================================= */}
      {/* MODAL 1: CHALLAN PDF PREVIEW MODAL                                        */}
      {/* ========================================================================= */}
      {selectedChallanPdf && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-xs p-4">
          <div className="w-full max-w-2xl rounded-2xl border border-border bg-card shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-150">
            <div className="flex items-center justify-between border-b border-border bg-muted/40 p-4">
              <div className="flex items-center gap-2">
                <FileText className="h-5 w-5 text-blue-500" />
                <div>
                  <h3 className="font-heading text-sm font-bold text-foreground">
                    Delivery Challan PDF Scan • {selectedChallanPdf.challan_no}
                  </h3>
                  <p className="text-xs text-muted-foreground">
                    Uploaded by Site Engineer {selectedChallanPdf.site_engineer_name || 'Divyesh Jasani'} via Pramukh Mobile App
                  </p>
                </div>
              </div>
              <button
                onClick={() => setSelectedChallanPdf(null)}
                className="rounded-lg p-1.5 text-muted-foreground hover:bg-muted transition-colors"
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            <div className="p-6 space-y-4 font-mono text-xs">
              <div className="rounded-xl border border-blue-500/30 bg-blue-500/5 p-4 space-y-2">
                <div className="flex justify-between font-bold border-b border-border pb-2">
                  <span>SUPPLIER: {selectedChallanPdf.vendor_name}</span>
                  <span className="text-primary">GRN: {selectedChallanPdf.grn_number}</span>
                </div>
                <div className="grid grid-cols-2 gap-2 text-muted-foreground pt-1">
                  <div>Challan No: <strong className="text-foreground">{selectedChallanPdf.challan_no}</strong></div>
                  <div>PO Number: <strong className="text-foreground">{selectedChallanPdf.po_number}</strong></div>
                  <div>Project Site: <strong className="text-foreground">{selectedChallanPdf.project_name}</strong></div>
                  <div>Godown Store: <strong className="text-foreground">{selectedChallanPdf.godown_name}</strong></div>
                  <div>Vehicle No: <strong className="text-foreground">{selectedChallanPdf.vehicle_no}</strong></div>
                  <div>Received Date: <strong className="text-foreground">{selectedChallanPdf.received_date}</strong></div>
                </div>
              </div>

              <div className="rounded-xl border border-border p-4 bg-muted/20 text-center space-y-3">
                <p className="text-muted-foreground text-xs">
                  📄 Digital Challan Document Signed &amp; Scanned on Site
                </p>
                <div className="inline-flex items-center gap-2 rounded-lg bg-emerald-500/10 border border-emerald-500/30 px-3 py-1.5 text-emerald-600 font-bold text-xs">
                  <ShieldCheck className="h-4 w-4" /> Stamp Verified &amp; Geotagged on Mobile App
                </div>
              </div>
            </div>

            <div className="flex items-center justify-end gap-3 border-t border-border bg-muted/20 p-4">
              <button
                onClick={() => setSelectedChallanPdf(null)}
                className="rounded-lg border border-border bg-background px-4 py-2 text-xs font-bold text-muted-foreground hover:bg-muted"
              >
                Close Preview
              </button>
              <button
                onClick={() => {
                  handleDownloadPdf(selectedChallanPdf);
                  setSelectedChallanPdf(null);
                }}
                className="inline-flex items-center gap-2 rounded-lg bg-blue-600 px-4 py-2 text-xs font-bold text-white hover:bg-blue-700 shadow-md"
              >
                <Download className="h-4 w-4" /> Download Challan PDF Document
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
