-- =====================================================================
-- Migration: Remove All Purchase Bills (Cleanup / Reset Script)
-- Description: Completely and safely removes all purchase bill records
--              and dependent transactional rows from Supabase.
-- =====================================================================

BEGIN;

-- 1. Delete dependent entries in matching & financial tables
DELETE FROM public.three_way_matches 
  WHERE vendor_bill_id IS NOT NULL;

DELETE FROM public.retention_releases 
  WHERE vendor_bill_id IS NOT NULL;

DELETE FROM public.payments 
  WHERE vendor_bill_id IS NOT NULL;

-- 2. Delete itemized lines
DELETE FROM public.vendor_bill_lines;

-- 3. Remove budget ledger postings generated by purchase bills (if present)
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'budget_ledger_entries') THEN
    DELETE FROM public.budget_ledger_entries WHERE source_table = 'vendor_bills';
  END IF;
END $$;

-- 4. Truncate / Delete all rows from vendor_bills master table
DELETE FROM public.vendor_bills;

COMMIT;
