import type { MasterBudgetCategory } from './budget';

export const CENTRAL_PARK_MASTER_BUDGET_CATEGORIES: MasterBudgetCategory[] = [
  {
    "id": "cat-1",
    "categoryName": "Site Development/Pre-Construction Work",
    "categoryCode": "SITE_DEVELOPMEN",
    "items": [
      {
        "id": "cp-item-1",
        "srNo": "1",
        "category": "Site Development/Pre-Construction Work",
        "item": "Temporary Site Barrication/Pre.Const. Work",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 500000,
        "cost": 500000,
        "costPerBua": 0.81,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-2",
        "srNo": "2",
        "category": "Site Development/Pre-Construction Work",
        "item": "Intial Site Development (Hoarding/Site Office/Leveling/Cleaning)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 5500000,
        "cost": 5500000,
        "costPerBua": 8.94,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-3",
        "srNo": "3",
        "category": "Site Development/Pre-Construction Work",
        "item": "GSB/Chaaru/Slag",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1500000,
        "cost": 1500000,
        "costPerBua": 2.44,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 7500000,
    "totalCostPerBua": 12.19
  },
  {
    "id": "cat-2",
    "categoryName": "Excavation/Backfilling and D-Wall/Pile Work",
    "categoryCode": "EXCAVATION_BACK",
    "items": [
      {
        "id": "cp-item-4",
        "srNo": "1",
        "category": "Excavation/Backfilling and D-Wall/Pile Work",
        "item": "Excavation/Backfilling",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 4480000,
        "cost": 4480000,
        "costPerBua": 7.28,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-5",
        "srNo": "2",
        "category": "Excavation/Backfilling and D-Wall/Pile Work",
        "item": "JCB/Poclain (Labour)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1650000,
        "cost": 1650000,
        "costPerBua": 2.68,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-6",
        "srNo": "3",
        "category": "Excavation/Backfilling and D-Wall/Pile Work",
        "item": "De-Watering",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 750000,
        "cost": 750000,
        "costPerBua": 1.22,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-7",
        "srNo": "2",
        "category": "Excavation/Backfilling and D-Wall/Pile Work",
        "item": "Diapharm Wall",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 46000000,
        "cost": 46000000,
        "costPerBua": 74.8,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 52880000,
    "totalCostPerBua": 85.98
  },
  {
    "id": "cat-3",
    "categoryName": "Civil Works",
    "categoryCode": "CIVIL_WORKS",
    "items": [
      {
        "id": "cp-item-8",
        "srNo": "1",
        "category": "Civil Works",
        "item": "Civil Labour Cost",
        "qtyRcc": 615000,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 615000,
        "unit": "Sqft",
        "rate": 1233.1,
        "cost": 758356500,
        "costPerBua": 1233.1,
        "scopeTag": "building_rcc",
        "itemType": "labour"
      },
      {
        "id": "cp-item-9",
        "srNo": "2",
        "category": "Civil Works",
        "item": "Rate Difference - (1.5% of Civil Cost)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 615000,
        "unit": "Sqft",
        "rate": 18.5,
        "cost": 11375347,
        "costPerBua": 18.5,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-10",
        "srNo": "3",
        "category": "Civil Works",
        "item": "Above Terrace Elevation Cost",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 8500000,
        "cost": 8500000,
        "costPerBua": 13.82,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-11",
        "srNo": "4",
        "category": "Civil Works",
        "item": "Core Cutting Cost",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 420000,
        "cost": 420000,
        "costPerBua": 0.68,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-12",
        "srNo": "5",
        "category": "Civil Works",
        "item": "Expansion Sheet",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 280000,
        "cost": 280000,
        "costPerBua": 0.46,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-13",
        "srNo": "6",
        "category": "Civil Works",
        "item": "Rebar Cost",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 2400000,
        "cost": 2400000,
        "costPerBua": 3.9,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 781331847,
    "totalCostPerBua": 1270.46
  },
  {
    "id": "cat-4",
    "categoryName": "Civil Materials",
    "categoryCode": "CIVIL_MATERIALS",
    "items": [
      {
        "id": "cp-item-14",
        "srNo": "1",
        "category": "Civil Materials",
        "item": "Cement - (Flooring Work+ Toilets,Terrace,Water Tanks,Podium Water Proofing)",
        "qtyRcc": null,
        "qtyFinishes": 46792.04,
        "qtyInfra": null,
        "qtyTotal": 46792.04,
        "unit": "Bags",
        "rate": 325,
        "cost": 15207414,
        "costPerBua": 24.73,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-15",
        "srNo": "2",
        "category": "Civil Materials",
        "item": "Sand - (Flooring Work+Toilets,Terrace,Water Tanks,Podium Water Proofing)",
        "qtyRcc": null,
        "qtyFinishes": 14475.62,
        "qtyInfra": null,
        "qtyTotal": 14475.62,
        "unit": "Ton",
        "rate": 1250,
        "cost": 18094527,
        "costPerBua": 29.42,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-16",
        "srNo": "3",
        "category": "Civil Materials",
        "item": "Metal 10mm & 20mm - (Terrace,Water Tanks,Podium Water Proofing)",
        "qtyRcc": null,
        "qtyFinishes": 3192.48,
        "qtyInfra": null,
        "qtyTotal": 3192.48,
        "unit": "Ton",
        "rate": 1200,
        "cost": 3830981,
        "costPerBua": 6.23,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-17",
        "srNo": "4",
        "category": "Civil Materials",
        "item": "Bricks-Waterproofing - (Toilets,Terrace,Water Tanks,Podium Water Proofing)",
        "qtyRcc": null,
        "qtyFinishes": 530606,
        "qtyInfra": null,
        "qtyTotal": 530606,
        "unit": "Nos.",
        "rate": 8,
        "cost": 4244848,
        "costPerBua": 6.9,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-18",
        "srNo": "5",
        "category": "Civil Materials",
        "item": "Chemical Bag For Tiles Cladding (All Toilets,Wash Area, Kitchen Wall Dedo)",
        "qtyRcc": null,
        "qtyFinishes": 14440.06,
        "qtyInfra": null,
        "qtyTotal": 14440.06,
        "unit": "Nos.",
        "rate": 435,
        "cost": 6281426,
        "costPerBua": 10.21,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-19",
        "srNo": "6",
        "category": "Civil Materials",
        "item": "Chemical Bag for Tile Flooring (6'X4' Flooring and 32\" X 64\")",
        "qtyRcc": null,
        "qtyFinishes": 12500,
        "qtyInfra": null,
        "qtyTotal": 12500,
        "unit": "Nos.",
        "rate": 435,
        "cost": 5437500,
        "costPerBua": 8.84,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 53096696,
    "totalCostPerBua": 86.33
  },
  {
    "id": "cat-5",
    "categoryName": "Waterproofing",
    "categoryCode": "WATERPROOFING",
    "items": [
      {
        "id": "cp-item-20",
        "srNo": "1",
        "category": "Waterproofing",
        "item": "Water Proofing Chemical PIDIFIN-90 Kg Set-(Flat-Toilet-Wash-Balcony)",
        "qtyRcc": null,
        "qtyFinishes": 452.13,
        "qtyInfra": null,
        "qtyTotal": 452.13,
        "unit": "Bags.",
        "rate": 6796.8,
        "cost": 3073013,
        "costPerBua": 5.0,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-21",
        "srNo": "2",
        "category": "Waterproofing",
        "item": "Water Proofing Terrace, UGWT & OHWT Chemical Labour + Material-(Base Coat)",
        "qtyRcc": null,
        "qtyFinishes": 42405.85,
        "qtyInfra": null,
        "qtyTotal": 42405.85,
        "unit": "Sqft",
        "rate": 133,
        "cost": 5639979,
        "costPerBua": 9.17,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-22",
        "srNo": "3",
        "category": "Waterproofing",
        "item": "Water Proofing Basement Retaining Wall",
        "qtyRcc": null,
        "qtyFinishes": 9500,
        "qtyInfra": null,
        "qtyTotal": 9500,
        "unit": "Sqft",
        "rate": 82.6,
        "cost": 784700,
        "costPerBua": 1.28,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-23",
        "srNo": "4",
        "category": "Waterproofing",
        "item": "GF. Floor Podium+1st Floor Water Proofing",
        "qtyRcc": null,
        "qtyFinishes": 42900,
        "qtyInfra": null,
        "qtyTotal": 42900,
        "unit": "Sqft",
        "rate": 118,
        "cost": 5062200,
        "costPerBua": 8.23,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-24",
        "srNo": "5",
        "category": "Waterproofing",
        "item": "Expansion Joint Treatment",
        "qtyRcc": null,
        "qtyFinishes": 210,
        "qtyInfra": null,
        "qtyTotal": 210,
        "unit": "Rmt",
        "rate": 6500,
        "cost": 1365000,
        "costPerBua": 2.22,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 15924892,
    "totalCostPerBua": 25.9
  },
  {
    "id": "cat-6",
    "categoryName": "Texture & Colour Work",
    "categoryCode": "TEXTURE_AND_COL",
    "items": [
      {
        "id": "cp-item-25",
        "srNo": "1",
        "category": "Texture & Colour Work",
        "item": "Flat Internal Putty Work (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 713057.13,
        "qtyInfra": null,
        "qtyTotal": 713057.13,
        "unit": "Sqft",
        "rate": 7.08,
        "cost": 5048444,
        "costPerBua": 8.21,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-26",
        "srNo": "2",
        "category": "Texture & Colour Work",
        "item": "Common Passage & Staircase Wall Texture & Colour Work",
        "qtyRcc": null,
        "qtyFinishes": 135784.72,
        "qtyInfra": null,
        "qtyTotal": 135784.72,
        "unit": "Sqft",
        "rate": 27.14,
        "cost": 3685197,
        "costPerBua": 5.99,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-27",
        "srNo": "3",
        "category": "Texture & Colour Work",
        "item": "Common Passage Ceiling Colour Work",
        "qtyRcc": null,
        "qtyFinishes": 61008.63,
        "qtyInfra": null,
        "qtyTotal": 61008.63,
        "unit": "Sqft",
        "rate": 28.32,
        "cost": 1727764,
        "costPerBua": 2.81,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-28",
        "srNo": "4",
        "category": "Texture & Colour Work",
        "item": "Lower + Upper  Basement + Gr Floor (Ceiling) Wall and Column & Slab - Birla Putty + Colour Work (Lab + Mat)",
        "qtyRcc": null,
        "qtyFinishes": 155609.77,
        "qtyInfra": null,
        "qtyTotal": 155609.77,
        "unit": "Sqft",
        "rate": 19.47,
        "cost": 3029722,
        "costPerBua": 4.93,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-29",
        "srNo": "5",
        "category": "Texture & Colour Work",
        "item": "Gr. Floor Colour (Labour + Material)",
        "qtyRcc": null,
        "qtyFinishes": 96040.63,
        "qtyInfra": null,
        "qtyTotal": 96040.63,
        "unit": "Sqft",
        "rate": 28.32,
        "cost": 2719871,
        "costPerBua": 4.42,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-30",
        "srNo": "6",
        "category": "Texture & Colour Work",
        "item": "Gr. Floor Column Texture  (Labour + Material)",
        "qtyRcc": null,
        "qtyFinishes": 34984.75,
        "qtyInfra": null,
        "qtyTotal": 34984.75,
        "unit": "Sqft",
        "rate": 27.14,
        "cost": 949486,
        "costPerBua": 1.54,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-31",
        "srNo": "7",
        "category": "Texture & Colour Work",
        "item": "Ramp Wall Colour (Labour + Material)",
        "qtyRcc": null,
        "qtyFinishes": 8060.85,
        "qtyInfra": null,
        "qtyTotal": 8060.85,
        "unit": "Sqft",
        "rate": 28.32,
        "cost": 228283,
        "costPerBua": 0.37,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-32",
        "srNo": "8",
        "category": "Texture & Colour Work",
        "item": "External Texture Colour + Primer (Labour + Material)",
        "qtyRcc": null,
        "qtyFinishes": 434632.78,
        "qtyInfra": null,
        "qtyTotal": 434632.78,
        "unit": "Sqft",
        "rate": 35.4,
        "cost": 15386000,
        "costPerBua": 25.02,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-33",
        "srNo": "9",
        "category": "Texture & Colour Work",
        "item": "Oil Paint",
        "qtyRcc": null,
        "qtyFinishes": 35000,
        "qtyInfra": null,
        "qtyTotal": 35000,
        "unit": "Sqft",
        "rate": 25,
        "cost": 875000,
        "costPerBua": 1.42,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 33649767,
    "totalCostPerBua": 54.71
  },
  {
    "id": "cat-7",
    "categoryName": "Gypsum Punning and False Ceiling",
    "categoryCode": "GYPSUM_PUNNING_",
    "items": [
      {
        "id": "cp-item-34",
        "srNo": "1",
        "category": "Gypsum Punning and False Ceiling",
        "item": "False Ceiling (Common Passage)",
        "qtyRcc": null,
        "qtyFinishes": 31021.85,
        "qtyInfra": null,
        "qtyTotal": 31021.85,
        "unit": "Sqft",
        "rate": 76.7,
        "cost": 2379376,
        "costPerBua": 3.87,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 2379376,
    "totalCostPerBua": 3.87
  },
  {
    "id": "cat-8",
    "categoryName": "Stone and Tiles Work Material",
    "categoryCode": "STONE_AND_TILES",
    "items": [
      {
        "id": "cp-item-35",
        "srNo": "1",
        "category": "Stone and Tiles Work Material",
        "item": "Flat Door/Window Frames, Kitchen Platform, Balcony Patta, Washbasin Shelf, Threshold - (Granite)  (Material)",
        "qtyRcc": null,
        "qtyFinishes": 102953,
        "qtyInfra": null,
        "qtyTotal": 102953,
        "unit": "Sqft",
        "rate": 84.96,
        "cost": 8746887,
        "costPerBua": 14.22,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-36",
        "srNo": "2",
        "category": "Stone and Tiles Work Material",
        "item": "Window Frames and Kitchen Platform and Vertical - Pink Marble (Material)",
        "qtyRcc": null,
        "qtyFinishes": 24498,
        "qtyInfra": null,
        "qtyTotal": 24498,
        "unit": "Sqft",
        "rate": 49.56,
        "cost": 1214121,
        "costPerBua": 1.97,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-37",
        "srNo": "3",
        "category": "Stone and Tiles Work Material",
        "item": "Flooring Vestibule, Living Room, Kitchen & Dining Room - (6' x 4') Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 130944.64,
        "qtyInfra": null,
        "qtyTotal": 130944.64,
        "unit": "Sqft",
        "rate": 68.44,
        "cost": 8961851,
        "costPerBua": 14.57,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-38",
        "srNo": "4",
        "category": "Stone and Tiles Work Material",
        "item": "Skirting Vestibule, Living Room, Kitchen & Dining Room - (6' X 4') Tiles (Material)-Skirting",
        "qtyRcc": null,
        "qtyFinishes": 6444.82,
        "qtyInfra": null,
        "qtyTotal": 6444.82,
        "unit": "Sqft",
        "rate": 68.44,
        "cost": 441084,
        "costPerBua": 0.72,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-39",
        "srNo": "5",
        "category": "Stone and Tiles Work Material",
        "item": "Flooring All Bedroom (1,2,3 and 4) - 32\" X 64\" Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 112892.86,
        "qtyInfra": null,
        "qtyTotal": 112892.86,
        "unit": "Sqft",
        "rate": 47.2,
        "cost": 5328543,
        "costPerBua": 8.66,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-40",
        "srNo": "6",
        "category": "Stone and Tiles Work Material",
        "item": "Flooring All Bedroom (1,2,3 and 4) -  32\" X 64\" Tiles (Material)-Skirting",
        "qtyRcc": null,
        "qtyFinishes": 9666.63,
        "qtyInfra": null,
        "qtyTotal": 9666.63,
        "unit": "Sqft",
        "rate": 47.2,
        "cost": 456265,
        "costPerBua": 0.74,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-41",
        "srNo": "7",
        "category": "Stone and Tiles Work Material",
        "item": "Flooring All Toilet,Wash Area -  2' X 4' Tiles  (Material)",
        "qtyRcc": null,
        "qtyFinishes": 34541.43,
        "qtyInfra": null,
        "qtyTotal": 34541.43,
        "unit": "Sqft",
        "rate": 47.2,
        "cost": 1630356,
        "costPerBua": 2.65,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-42",
        "srNo": "8",
        "category": "Stone and Tiles Work Material",
        "item": "Dado All Toilet, Wash Area & Kitchen - 2' X 4'  Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 298064.94,
        "qtyInfra": null,
        "qtyTotal": 298064.94,
        "unit": "Sqft",
        "rate": 47.2,
        "cost": 14068665,
        "costPerBua": 22.88,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-43",
        "srNo": "9",
        "category": "Stone and Tiles Work Material",
        "item": "Flooring Balcony Deck - 200 X 1200 Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 17260.46,
        "qtyInfra": null,
        "qtyTotal": 17260.46,
        "unit": "Sqft",
        "rate": 64.9,
        "cost": 1120204,
        "costPerBua": 1.82,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-44",
        "srNo": "10",
        "category": "Stone and Tiles Work Material",
        "item": "Common Passage Flooring - 600 X 1200 Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 35165.99,
        "qtyInfra": null,
        "qtyTotal": 35165.99,
        "unit": "Sqft",
        "rate": 43.66,
        "cost": 1535347,
        "costPerBua": 2.5,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-45",
        "srNo": "11",
        "category": "Stone and Tiles Work Material",
        "item": "Common Passage Dado - 600 X 1200 Tiles (Material)",
        "qtyRcc": null,
        "qtyFinishes": 20468,
        "qtyInfra": null,
        "qtyTotal": 20468,
        "unit": "Sqft",
        "rate": 43.66,
        "cost": 893633,
        "costPerBua": 1.45,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-46",
        "srNo": "12",
        "category": "Stone and Tiles Work Material",
        "item": "Staircase Granite",
        "qtyRcc": null,
        "qtyFinishes": 52555.05,
        "qtyInfra": null,
        "qtyTotal": 52555.05,
        "unit": "Sqft",
        "rate": 84.96,
        "cost": 4465077,
        "costPerBua": 7.26,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-47",
        "srNo": "13",
        "category": "Stone and Tiles Work Material",
        "item": "Staircase Mid Landing Flooring",
        "qtyRcc": null,
        "qtyFinishes": 16716,
        "qtyInfra": null,
        "qtyTotal": 16716,
        "unit": "Sqft",
        "rate": 47.2,
        "cost": 788995,
        "costPerBua": 1.28,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-48",
        "srNo": "14",
        "category": "Stone and Tiles Work Material",
        "item": "Comm Passage Lift Frame, Duct Frames - Granite",
        "qtyRcc": null,
        "qtyFinishes": 10306.79,
        "qtyInfra": null,
        "qtyTotal": 10306.79,
        "unit": "Sqft",
        "rate": 84.96,
        "cost": 875665,
        "costPerBua": 1.42,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-49",
        "srNo": "15",
        "category": "Stone and Tiles Work Material",
        "item": "Building Portion Parking Tiles-Material",
        "qtyRcc": null,
        "qtyFinishes": 13794.07,
        "qtyInfra": null,
        "qtyTotal": 13794.07,
        "unit": "Sqft",
        "rate": 53.1,
        "cost": 732465,
        "costPerBua": 1.19,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-50",
        "srNo": "16",
        "category": "Stone and Tiles Work Material",
        "item": "Ground Floor Non Building Parking Portion Tiles",
        "qtyRcc": null,
        "qtyFinishes": 27429.71,
        "qtyInfra": null,
        "qtyTotal": 27429.71,
        "unit": "Sqft",
        "rate": 53.1,
        "cost": 1456517,
        "costPerBua": 2.37,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-51",
        "srNo": "17",
        "category": "Stone and Tiles Work Material",
        "item": "Building Parking Around Granite Patta",
        "qtyRcc": null,
        "qtyFinishes": 2239.29,
        "qtyInfra": null,
        "qtyTotal": 2239.29,
        "unit": "Sqft",
        "rate": 84.96,
        "cost": 190250,
        "costPerBua": 0.31,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 52905925,
    "totalCostPerBua": 86.01
  },
  {
    "id": "cat-9",
    "categoryName": "Stone and Tiles Work Labour",
    "categoryCode": "STONE_AND_TILES",
    "items": [
      {
        "id": "cp-item-52",
        "srNo": "1",
        "category": "Stone and Tiles Work Labour",
        "item": "Flat Door/Window Frames /Commen Passage Elevation Frame/Staircase passage window Frame//Service Duct/W.B. Shelves Lift Frames - (Granite)",
        "qtyRcc": null,
        "qtyFinishes": 159017.61,
        "qtyInfra": null,
        "qtyTotal": 159017.61,
        "unit": "Rft",
        "rate": 75,
        "cost": 11926321,
        "costPerBua": 19.39,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-53",
        "srNo": "2",
        "category": "Stone and Tiles Work Labour",
        "item": "Flat Window Frame Work Pink Marble - Labour",
        "qtyRcc": null,
        "qtyFinishes": 42351.62,
        "qtyInfra": null,
        "qtyTotal": 42351.62,
        "unit": "Rft",
        "rate": 50,
        "cost": 2117581,
        "costPerBua": 3.44,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-54",
        "srNo": "3",
        "category": "Stone and Tiles Work Labour",
        "item": "Frame Dhar Polish Labour (Lift Door, Door & Window Frame, Balcony Sill)",
        "qtyRcc": null,
        "qtyFinishes": 208456.69,
        "qtyInfra": null,
        "qtyTotal": 208456.69,
        "unit": "Rft",
        "rate": 18.88,
        "cost": 3935662,
        "costPerBua": 6.4,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-55",
        "srNo": "4",
        "category": "Stone and Tiles Work Labour",
        "item": "Kitchen Platform (Granite) (Material)",
        "qtyRcc": null,
        "qtyFinishes": 4054.71,
        "qtyInfra": null,
        "qtyTotal": 4054.71,
        "unit": "Rft",
        "rate": 1050,
        "cost": 4257445,
        "costPerBua": 6.92,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-56",
        "srNo": "5",
        "category": "Stone and Tiles Work Labour",
        "item": "Flooring Vestibule, Living Room, Kitchen & Dining Room - 6' X 4' Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 119040.58,
        "qtyInfra": null,
        "qtyTotal": 119040.58,
        "unit": "Sqft",
        "rate": 80,
        "cost": 9523247,
        "costPerBua": 15.48,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-57",
        "srNo": "6",
        "category": "Stone and Tiles Work Labour",
        "item": "Skirting Vestibule, Living Room, Kitchen & Dining Room - 6' X 4' Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 23804.4,
        "qtyInfra": null,
        "qtyTotal": 23804.4,
        "unit": "Rft",
        "rate": 85,
        "cost": 2023374,
        "costPerBua": 3.29,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-58",
        "srNo": "7",
        "category": "Stone and Tiles Work Labour",
        "item": "Flooring All Bedroom - 32\" X 64\" Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 102629.87,
        "qtyInfra": null,
        "qtyTotal": 102629.87,
        "unit": "Sqft",
        "rate": 65,
        "cost": 6670942,
        "costPerBua": 10.85,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-59",
        "srNo": "8",
        "category": "Stone and Tiles Work Labour",
        "item": "Skirting All Bedroom - 32\" X 64\" Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 35704.37,
        "qtyInfra": null,
        "qtyTotal": 35704.37,
        "unit": "Rft",
        "rate": 68,
        "cost": 2427897,
        "costPerBua": 3.95,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-60",
        "srNo": "9",
        "category": "Stone and Tiles Work Labour",
        "item": "Flooring All Toilet, Wash Area, Store Room 2' X 4' Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 31401.3,
        "qtyInfra": null,
        "qtyTotal": 31401.3,
        "unit": "Sqft",
        "rate": 45,
        "cost": 1413059,
        "costPerBua": 2.3,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-61",
        "srNo": "10",
        "category": "Stone and Tiles Work Labour",
        "item": "Dado All Toilet, Wash Area & Kitchen 2' X 4' Tiles  (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 270968.13,
        "qtyInfra": null,
        "qtyTotal": 270968.13,
        "unit": "Sqft",
        "rate": 50,
        "cost": 13548406,
        "costPerBua": 22.03,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-62",
        "srNo": "11",
        "category": "Stone and Tiles Work Labour",
        "item": "Flooring Balcony - 200 X 1200 Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 15691.33,
        "qtyInfra": null,
        "qtyTotal": 15691.33,
        "unit": "Sqft",
        "rate": 51.92,
        "cost": 814694,
        "costPerBua": 1.32,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-63",
        "srNo": "12",
        "category": "Stone and Tiles Work Labour",
        "item": "Living Room Balcony Sill - Granite Patta (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 4235.14,
        "qtyInfra": null,
        "qtyTotal": 4235.14,
        "unit": "Rft",
        "rate": 75,
        "cost": 317635,
        "costPerBua": 0.52,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-64",
        "srNo": "13",
        "category": "Stone and Tiles Work Labour",
        "item": "Bedroom Standing Balcony Sill - Granite Patta (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 20088.85,
        "qtyInfra": null,
        "qtyTotal": 20088.85,
        "unit": "Rft",
        "rate": 75,
        "cost": 1506664,
        "costPerBua": 2.45,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-65",
        "srNo": "14",
        "category": "Stone and Tiles Work Labour",
        "item": "Common Passage Flooring - 600 X 1200 Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 31969.08,
        "qtyInfra": null,
        "qtyTotal": 31969.08,
        "unit": "Sqft",
        "rate": 45,
        "cost": 1438609,
        "costPerBua": 2.34,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-66",
        "srNo": "15",
        "category": "Stone and Tiles Work Labour",
        "item": "Common Passage Dado - 600 X 1200 Tiles (Labour)",
        "qtyRcc": null,
        "qtyFinishes": 18607.27,
        "qtyInfra": null,
        "qtyTotal": 18607.27,
        "unit": "Sqft",
        "rate": 50,
        "cost": 930364,
        "costPerBua": 1.51,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-67",
        "srNo": "16",
        "category": "Stone and Tiles Work Labour",
        "item": "Staircase Granite With Mid Landing Flooring Work Labour",
        "qtyRcc": null,
        "qtyFinishes": 54897.64,
        "qtyInfra": null,
        "qtyTotal": 54897.64,
        "unit": "Sqft",
        "rate": 75,
        "cost": 4117323,
        "costPerBua": 6.69,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-68",
        "srNo": "17",
        "category": "Stone and Tiles Work Labour",
        "item": "Staircase Riser and Tread Moulding Work Labour",
        "qtyRcc": null,
        "qtyFinishes": 40362.37,
        "qtyInfra": null,
        "qtyTotal": 40362.37,
        "unit": "Rft",
        "rate": 75,
        "cost": 3027178,
        "costPerBua": 4.92,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-69",
        "srNo": "18",
        "category": "Stone and Tiles Work Labour",
        "item": "Building Portion Parking Tiles-Material",
        "qtyRcc": null,
        "qtyFinishes": 12540.06,
        "qtyInfra": null,
        "qtyTotal": 12540.06,
        "unit": "Sqft",
        "rate": 33.04,
        "cost": 414324,
        "costPerBua": 0.67,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-70",
        "srNo": "19",
        "category": "Stone and Tiles Work Labour",
        "item": "Ground Floor Non Building Parking Portion Tiles",
        "qtyRcc": null,
        "qtyFinishes": 24936.1,
        "qtyInfra": null,
        "qtyTotal": 24936.1,
        "unit": "Sqft",
        "rate": 33.04,
        "cost": 823889,
        "costPerBua": 1.34,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-71",
        "srNo": "20",
        "category": "Stone and Tiles Work Labour",
        "item": "Building Parking Around Granite Patta",
        "qtyRcc": null,
        "qtyFinishes": 5274.24,
        "qtyInfra": null,
        "qtyTotal": 5274.24,
        "unit": "Rft",
        "rate": 41.3,
        "cost": 217826,
        "costPerBua": 0.35,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-72",
        "srNo": "21",
        "category": "Stone and Tiles Work Labour",
        "item": "Flooring PCC Work - Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 221670.46,
        "unit": "Sqft",
        "rate": 17,
        "cost": 3768398,
        "costPerBua": 6.13,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-73",
        "srNo": "23",
        "category": "Stone and Tiles Work Labour",
        "item": "Joint Filling - Epoxy",
        "qtyRcc": null,
        "qtyFinishes": 362143.29,
        "qtyInfra": null,
        "qtyTotal": 362143.29,
        "unit": "Rft",
        "rate": 8,
        "cost": 2897146,
        "costPerBua": 4.71,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-74",
        "srNo": "24",
        "category": "Stone and Tiles Work Labour",
        "item": "Miscellaneous Items (Spacers, Fevikwick etc)",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1000000,
        "cost": 1000000,
        "costPerBua": 1.63,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 79117984,
    "totalCostPerBua": 128.63
  },
  {
    "id": "cat-10",
    "categoryName": "Electrical",
    "categoryCode": "ELECTRICAL",
    "items": [
      {
        "id": "cp-item-75",
        "srNo": "1",
        "category": "Electrical",
        "item": "Electrical Works Flat (Material + Labour)-3BHK",
        "qtyRcc": null,
        "qtyFinishes": 102,
        "qtyInfra": null,
        "qtyTotal": 102,
        "unit": "Nos.",
        "rate": 123900,
        "cost": 12637800,
        "costPerBua": 20.55,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-76",
        "srNo": "2",
        "category": "Electrical",
        "item": "Electrical Works Flat (Material + Labour)-4BHK",
        "qtyRcc": null,
        "qtyFinishes": 64,
        "qtyInfra": null,
        "qtyTotal": 64,
        "unit": "Nos.",
        "rate": 141600,
        "cost": 9062400,
        "costPerBua": 14.74,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-77",
        "srNo": "3",
        "category": "Electrical",
        "item": "Electrical Works Flat (Material + Labour)-PENTHOUSE-A-D Building",
        "qtyRcc": null,
        "qtyFinishes": 4,
        "qtyInfra": null,
        "qtyTotal": 4,
        "unit": "Nos.",
        "rate": 165200,
        "cost": 660800,
        "costPerBua": 1.07,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-78",
        "srNo": "4",
        "category": "Electrical",
        "item": "Electrical Works Flat (Material + Labour)-PENTHOUSE-B-C Building",
        "qtyRcc": null,
        "qtyFinishes": 6,
        "qtyInfra": null,
        "qtyTotal": 6,
        "unit": "Nos.",
        "rate": 171100,
        "cost": 1026600,
        "costPerBua": 1.67,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-79",
        "srNo": "5",
        "category": "Electrical",
        "item": "Commom Passage & Staircase Landing Lights",
        "qtyRcc": null,
        "qtyFinishes": 540,
        "qtyInfra": null,
        "qtyTotal": 540,
        "unit": "Nos.",
        "rate": 1200,
        "cost": 648000,
        "costPerBua": 1.05,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-80",
        "srNo": "6",
        "category": "Electrical",
        "item": "D.G. Set",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 2,
        "unit": "Nos.",
        "rate": 1770000,
        "cost": 3540000,
        "costPerBua": 5.76,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-81",
        "srNo": "7",
        "category": "Electrical",
        "item": "Street Lights",
        "qtyRcc": null,
        "qtyFinishes": 45,
        "qtyInfra": null,
        "qtyTotal": 45,
        "unit": "Nos.",
        "rate": 23600,
        "cost": 1062000,
        "costPerBua": 1.73,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-82",
        "srNo": "8",
        "category": "Electrical",
        "item": "Garden Lights Bollards",
        "qtyRcc": null,
        "qtyFinishes": 25,
        "qtyInfra": null,
        "qtyTotal": 25,
        "unit": "Nos.",
        "rate": 9440,
        "cost": 236000,
        "costPerBua": 0.38,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-83",
        "srNo": "9",
        "category": "Electrical",
        "item": "Foot Lights - Ramps/Planters",
        "qtyRcc": null,
        "qtyFinishes": 100,
        "qtyInfra": null,
        "qtyTotal": 100,
        "unit": "Nos.",
        "rate": 2655,
        "cost": 265500,
        "costPerBua": 0.43,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-84",
        "srNo": "10",
        "category": "Electrical",
        "item": "LED Strip Light",
        "qtyRcc": null,
        "qtyFinishes": 250,
        "qtyInfra": null,
        "qtyTotal": 250,
        "unit": "Rmt",
        "rate": 1600,
        "cost": 400000,
        "costPerBua": 0.65,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-85",
        "srNo": "11",
        "category": "Electrical",
        "item": "Main Entry Gate Lights",
        "qtyRcc": null,
        "qtyFinishes": 10,
        "qtyInfra": null,
        "qtyTotal": 10,
        "unit": "Nos.",
        "rate": 3000,
        "cost": 30000,
        "costPerBua": 0.05,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-86",
        "srNo": "12",
        "category": "Electrical",
        "item": "Watchman Cabin Lights",
        "qtyRcc": null,
        "qtyFinishes": 6,
        "qtyInfra": null,
        "qtyTotal": 6,
        "unit": "Nos.",
        "rate": 1200,
        "cost": 7200,
        "costPerBua": 0.01,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-87",
        "srNo": "13",
        "category": "Electrical",
        "item": "Parking Lights Basement-Ground Floor (Lab + Mat)",
        "qtyRcc": null,
        "qtyFinishes": 450,
        "qtyInfra": null,
        "qtyTotal": 450,
        "unit": "Nos.",
        "rate": 1000,
        "cost": 450000,
        "costPerBua": 0.73,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-88",
        "srNo": "14",
        "category": "Electrical",
        "item": "Compound Wall Bracket Lights",
        "qtyRcc": null,
        "qtyFinishes": 135,
        "qtyInfra": null,
        "qtyTotal": 135,
        "unit": "Nos.",
        "rate": 3000,
        "cost": 405000,
        "costPerBua": 0.66,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-89",
        "srNo": "15",
        "category": "Electrical",
        "item": "Spike Lights",
        "qtyRcc": null,
        "qtyFinishes": 100,
        "qtyInfra": null,
        "qtyTotal": 100,
        "unit": "Nos.",
        "rate": 2950,
        "cost": 295000,
        "costPerBua": 0.48,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-90",
        "srNo": "16",
        "category": "Electrical",
        "item": "Decorative Lights",
        "qtyRcc": null,
        "qtyFinishes": 4,
        "qtyInfra": null,
        "qtyTotal": 4,
        "unit": "LS",
        "rate": 150000,
        "cost": 600000,
        "costPerBua": 0.98,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-91",
        "srNo": "17",
        "category": "Electrical",
        "item": "LT Cables & Other Materials",
        "qtyRcc": null,
        "qtyFinishes": 600,
        "qtyInfra": null,
        "qtyTotal": 600,
        "unit": "Rmt",
        "rate": 1750,
        "cost": 1050000,
        "costPerBua": 1.71,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-92",
        "srNo": "18",
        "category": "Electrical",
        "item": "Cable Tray",
        "qtyRcc": null,
        "qtyFinishes": 600,
        "qtyInfra": null,
        "qtyTotal": 600,
        "unit": "Rmt",
        "rate": 1200,
        "cost": 720000,
        "costPerBua": 1.17,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-93",
        "srNo": "19",
        "category": "Electrical",
        "item": "CAT 6 Wire + Labour",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 400000,
        "cost": 400000,
        "costPerBua": 0.65,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-94",
        "srNo": "20",
        "category": "Electrical",
        "item": "Meter Room Electric Panel",
        "qtyRcc": null,
        "qtyFinishes": 5,
        "qtyInfra": null,
        "qtyTotal": 5,
        "unit": "LS",
        "rate": 324500,
        "cost": 1622500,
        "costPerBua": 2.64,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-95",
        "srNo": "21",
        "category": "Electrical",
        "item": "Basement & COP Electric Work Labour with Material",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 3750000,
        "cost": 3750000,
        "costPerBua": 6.1,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-96",
        "srNo": "22",
        "category": "Electrical",
        "item": "Temporary Site Work",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 2000000,
        "cost": 2000000,
        "costPerBua": 3.25,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-97",
        "srNo": "23",
        "category": "Electrical",
        "item": "RMU Cost",
        "qtyRcc": null,
        "qtyFinishes": 2,
        "qtyInfra": null,
        "qtyTotal": 2,
        "unit": "Nos",
        "rate": 1250000,
        "cost": 2500000,
        "costPerBua": 4.07,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 43368800,
    "totalCostPerBua": 70.53
  },
  {
    "id": "cat-11",
    "categoryName": "Plumbing",
    "categoryCode": "PLUMBING",
    "items": [
      {
        "id": "cp-item-98",
        "srNo": "1",
        "category": "Plumbing",
        "item": "CP & Sanitary Fittings (Material + Labour)-3BHK",
        "qtyRcc": null,
        "qtyFinishes": 102,
        "qtyInfra": null,
        "qtyTotal": 102,
        "unit": "Nos.",
        "rate": 85000,
        "cost": 8670000,
        "costPerBua": 14.1,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-99",
        "srNo": "2",
        "category": "Plumbing",
        "item": "CP & Sanitary Fittings (Material + Labour)-4BHK",
        "qtyRcc": null,
        "qtyFinishes": 64,
        "qtyInfra": null,
        "qtyTotal": 64,
        "unit": "Nos.",
        "rate": 110000,
        "cost": 7040000,
        "costPerBua": 11.45,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-100",
        "srNo": "3",
        "category": "Plumbing",
        "item": "CP & Sanitary Fittings (Material + Labour)-PENTHOUSE-A-D Building",
        "qtyRcc": null,
        "qtyFinishes": 4,
        "qtyInfra": null,
        "qtyTotal": 4,
        "unit": "Nos.",
        "rate": 130000,
        "cost": 520000,
        "costPerBua": 0.85,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-101",
        "srNo": "4",
        "category": "Plumbing",
        "item": "CP & Sanitary Fittings (Material + Labour)-PENTHOUSE-B-C Building",
        "qtyRcc": null,
        "qtyFinishes": 6,
        "qtyInfra": null,
        "qtyTotal": 6,
        "unit": "Nos.",
        "rate": 130000,
        "cost": 780000,
        "costPerBua": 1.27,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-102",
        "srNo": "5",
        "category": "Plumbing",
        "item": "Plumbing Materials - Inside Flat and Vertical Lines Work (Upvc/Cpvc, PVC Pipes, Valves, Traps, Clamps, MABT, FABT, PRV, ARV, Solonide, Rack Bolts, Tafflon Tape, Whitec Cement, Canvas Pipes, Temp Motors for Dewatering, Borewell etc.)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 615000,
        "unit": "Sqft",
        "rate": 40,
        "cost": 24600000,
        "costPerBua": 40,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-103",
        "srNo": "6",
        "category": "Plumbing",
        "item": "FRP ManHole Cover",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 150,
        "unit": "Nos.",
        "rate": 8000,
        "cost": 1200000,
        "costPerBua": 1.95,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-104",
        "srNo": "7",
        "category": "Plumbing",
        "item": "Basement Storm WaterLine Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 750000,
        "cost": 750000,
        "costPerBua": 1.22,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-105",
        "srNo": "8",
        "category": "Plumbing",
        "item": "Podium-Basement Storm Water Line Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 530000,
        "cost": 530000,
        "costPerBua": 0.86,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-106",
        "srNo": "9",
        "category": "Plumbing",
        "item": "Water Supply Looping Line Work Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1200000,
        "cost": 1200000,
        "costPerBua": 1.95,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-107",
        "srNo": "10",
        "category": "Plumbing",
        "item": "Outer Drainage Line Work Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1100000,
        "cost": 1100000,
        "costPerBua": 1.79,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-108",
        "srNo": "11",
        "category": "Plumbing",
        "item": "Planter Drain and Water Supply Line Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 530000,
        "cost": 530000,
        "costPerBua": 0.86,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-109",
        "srNo": "12",
        "category": "Plumbing",
        "item": "Basement Storm WaterLine Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 600000,
        "cost": 600000,
        "costPerBua": 0.98,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-110",
        "srNo": "13",
        "category": "Plumbing",
        "item": "Podium-Basement Storm Water Line Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 350000,
        "cost": 350000,
        "costPerBua": 0.57,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-111",
        "srNo": "14",
        "category": "Plumbing",
        "item": "Water Supply Looping Line Work Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 750000,
        "cost": 750000,
        "costPerBua": 1.22,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-112",
        "srNo": "15",
        "category": "Plumbing",
        "item": "Outer Drainage Line Work Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 600000,
        "cost": 600000,
        "costPerBua": 0.98,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-113",
        "srNo": "16",
        "category": "Plumbing",
        "item": "Planter Drain and Water Supply Line Labour",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 150000,
        "cost": 150000,
        "costPerBua": 0.24,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-114",
        "srNo": "17",
        "category": "Plumbing",
        "item": "Pnematic Pumps",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 7000000,
        "cost": 7000000,
        "costPerBua": 11.38,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-115",
        "srNo": "18",
        "category": "Plumbing",
        "item": "Water Tankers",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1100000,
        "cost": 1100000,
        "costPerBua": 1.79,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-116",
        "srNo": "19",
        "category": "Plumbing",
        "item": "Construction Water Pumping System",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 250000,
        "cost": 250000,
        "costPerBua": 0.41,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-117",
        "srNo": "20",
        "category": "Plumbing",
        "item": "Temporary Line and Borewell Cost",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 700000,
        "cost": 700000,
        "costPerBua": 1.14,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-118",
        "srNo": "21",
        "category": "Plumbing",
        "item": "Mud Pumps",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 450000,
        "cost": 450000,
        "costPerBua": 0.73,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-119",
        "srNo": "22",
        "category": "Plumbing",
        "item": "Plumbing Labour-(Material + Labour)-3BHK",
        "qtyRcc": null,
        "qtyFinishes": 102,
        "qtyInfra": null,
        "qtyTotal": 102,
        "unit": "Nos.",
        "rate": 60000,
        "cost": 6120000,
        "costPerBua": 9.95,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-120",
        "srNo": "23",
        "category": "Plumbing",
        "item": "Plumbing Labour-(Material + Labour)-4BHK",
        "qtyRcc": null,
        "qtyFinishes": 64,
        "qtyInfra": null,
        "qtyTotal": 64,
        "unit": "Nos.",
        "rate": 80000,
        "cost": 5120000,
        "costPerBua": 8.33,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-121",
        "srNo": "24",
        "category": "Plumbing",
        "item": "Plumbing Labour-(Material + Labour)-PENTHOUSE-A-D Building",
        "qtyRcc": null,
        "qtyFinishes": 4,
        "qtyInfra": null,
        "qtyTotal": 4,
        "unit": "Nos.",
        "rate": 105000,
        "cost": 420000,
        "costPerBua": 0.68,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-122",
        "srNo": "25",
        "category": "Plumbing",
        "item": "Plumbing Labour-(Material + Labour)-PENTHOUSE-B-C Building",
        "qtyRcc": null,
        "qtyFinishes": 6,
        "qtyInfra": null,
        "qtyTotal": 6,
        "unit": "Nos.",
        "rate": 105000,
        "cost": 630000,
        "costPerBua": 1.02,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      }
    ],
    "totalCost": 71160000,
    "totalCostPerBua": 115.72
  },
  {
    "id": "cat-12",
    "categoryName": "Fabrication Work",
    "categoryCode": "FABRICATION_WOR",
    "items": [
      {
        "id": "cp-item-123",
        "srNo": "1",
        "category": "Fabrication Work",
        "item": "AC Platforms",
        "qtyRcc": null,
        "qtyFinishes": 364,
        "qtyInfra": null,
        "qtyTotal": 364,
        "unit": "Nos.",
        "rate": 5000,
        "cost": 1820000,
        "costPerBua": 2.96,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-124",
        "srNo": "2",
        "category": "Fabrication Work",
        "item": "Staircase Railing",
        "qtyRcc": null,
        "qtyFinishes": 8,
        "qtyInfra": null,
        "qtyTotal": 8,
        "unit": "Nos.",
        "rate": 500000,
        "cost": 4000000,
        "costPerBua": 6.5,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-125",
        "srNo": "3",
        "category": "Fabrication Work",
        "item": "Lanndscape Gazebo",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 2,
        "qtyTotal": 2,
        "unit": "Nos.",
        "rate": 450000,
        "cost": 900000,
        "costPerBua": 1.46,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-126",
        "srNo": "4",
        "category": "Fabrication Work",
        "item": "Top Duct Covering",
        "qtyRcc": null,
        "qtyFinishes": 4,
        "qtyInfra": null,
        "qtyTotal": 4,
        "unit": "LS",
        "rate": 150000,
        "cost": 600000,
        "costPerBua": 0.98,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-127",
        "srNo": "5",
        "category": "Fabrication Work",
        "item": "Temporary Site Barrication",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 250000,
        "cost": 250000,
        "costPerBua": 0.41,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-128",
        "srNo": "6",
        "category": "Fabrication Work",
        "item": "Terrace & Pumproom Doors",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 4,
        "qtyTotal": 4,
        "unit": "LS",
        "rate": 135000,
        "cost": 540000,
        "costPerBua": 0.88,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-129",
        "srNo": "7",
        "category": "Fabrication Work",
        "item": "OHWT and UGWT Tank Chambers",
        "qtyRcc": null,
        "qtyFinishes": 24,
        "qtyInfra": null,
        "qtyTotal": 24,
        "unit": "Nos.",
        "rate": 4000,
        "cost": 96000,
        "costPerBua": 0.16,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-130",
        "srNo": "8",
        "category": "Fabrication Work",
        "item": "Entry Gate Fabrication Work",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 600000,
        "cost": 600000,
        "costPerBua": 0.98,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-131",
        "srNo": "9",
        "category": "Fabrication Work",
        "item": "Terrace Top Pergola Fabrication",
        "qtyRcc": null,
        "qtyFinishes": 2289.46,
        "qtyInfra": 2289.46,
        "qtyTotal": 4578.92,
        "unit": "Sq.ft",
        "rate": 1250,
        "cost": 2861825,
        "costPerBua": 4.65,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-132",
        "srNo": "10",
        "category": "Fabrication Work",
        "item": "Fabrication for Soil Supporting - (Protection during Rain)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 750000,
        "cost": 750000,
        "costPerBua": 1.22,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 12417825,
    "totalCostPerBua": 20.2
  },
  {
    "id": "cat-13",
    "categoryName": "Fa\u00e7ade Work",
    "categoryCode": "FA\u00c7ADE_WORK",
    "items": [
      {
        "id": "cp-item-133",
        "srNo": "1",
        "category": "Fa\u00e7ade Work",
        "item": "Elevation Louvers Labour and Material",
        "qtyRcc": null,
        "qtyFinishes": 25726.44,
        "qtyInfra": null,
        "qtyTotal": 25726.44,
        "unit": "Sqft",
        "rate": 206.5,
        "cost": 5312511,
        "costPerBua": 8.64,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-134",
        "srNo": "2",
        "category": "Fa\u00e7ade Work",
        "item": "Elevation Stair passage side Louvers Labour and Material",
        "qtyRcc": null,
        "qtyFinishes": 13484.15,
        "qtyInfra": null,
        "qtyTotal": 13484.15,
        "unit": "Sqft",
        "rate": 206.5,
        "cost": 2784477,
        "costPerBua": 4.53,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-135",
        "srNo": "3",
        "category": "Fa\u00e7ade Work",
        "item": "Z Louvers Labour and Material (Internal Passages)",
        "qtyRcc": null,
        "qtyFinishes": 6701.15,
        "qtyInfra": null,
        "qtyTotal": 6701.15,
        "unit": "Sqft",
        "rate": 194.7,
        "cost": 1304714,
        "costPerBua": 2.12,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-136",
        "srNo": "4",
        "category": "Fa\u00e7ade Work",
        "item": "Elevation Deck and Standing Balcony Glass Railing Labour and Material",
        "qtyRcc": null,
        "qtyFinishes": 25982.72,
        "qtyInfra": null,
        "qtyTotal": 25982.72,
        "unit": "Sqft",
        "rate": 802.4,
        "cost": 20848538,
        "costPerBua": 33.9,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-137",
        "srNo": "5",
        "category": "Fa\u00e7ade Work",
        "item": "Elevation Standing Balcony MS Railing Labour and Material-Bedroom",
        "qtyRcc": null,
        "qtyFinishes": 14833.14,
        "qtyInfra": null,
        "qtyTotal": 14833.14,
        "unit": "Sqft",
        "rate": 350,
        "cost": 5191598,
        "costPerBua": 8.44,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-138",
        "srNo": "6",
        "category": "Fa\u00e7ade Work",
        "item": "1st Floor External Wall Tiles Cladding",
        "qtyRcc": null,
        "qtyFinishes": 22927.32,
        "qtyInfra": null,
        "qtyTotal": 22927.32,
        "unit": "Sqft",
        "rate": 225,
        "cost": 5158647,
        "costPerBua": 8.39,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 40600485,
    "totalCostPerBua": 66.02
  },
  {
    "id": "cat-14",
    "categoryName": "Fa\u00e7ade",
    "categoryCode": "FA\u00c7ADE",
    "items": [
      {
        "id": "cp-item-139",
        "srNo": "1",
        "category": "Fa\u00e7ade",
        "item": "Living Room Balcony Ceiling Labour and Material-ACP Sheet",
        "qtyRcc": null,
        "qtyFinishes": 9500,
        "qtyInfra": null,
        "qtyTotal": 9500,
        "unit": "Sqft",
        "rate": 413,
        "cost": 3923500,
        "costPerBua": 6.38,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      }
    ],
    "totalCost": 3923500,
    "totalCostPerBua": 6.38
  },
  {
    "id": "cat-15",
    "categoryName": "Door Hardware and Furniture Works",
    "categoryCode": "DOOR_HARDWARE_A",
    "items": [
      {
        "id": "cp-item-140",
        "srNo": "1",
        "category": "Door Hardware and Furniture Works",
        "item": "Laminate Doors",
        "qtyRcc": null,
        "qtyFinishes": 1890,
        "qtyInfra": null,
        "qtyTotal": 1890,
        "unit": "Nos.",
        "rate": 4897,
        "cost": 9255330,
        "costPerBua": 15.05,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-141",
        "srNo": "2",
        "category": "Door Hardware and Furniture Works",
        "item": "Hardwares (Locks, Hinges, Screw, Magnet, Handle etc.)",
        "qtyRcc": null,
        "qtyFinishes": 1890,
        "qtyInfra": null,
        "qtyTotal": 1890,
        "unit": "Nos",
        "rate": 1770,
        "cost": 3345300,
        "costPerBua": 5.44,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-142",
        "srNo": "3",
        "category": "Door Hardware and Furniture Works",
        "item": "Door Fitting Labour",
        "qtyRcc": null,
        "qtyFinishes": 1890,
        "qtyInfra": null,
        "qtyTotal": 1890,
        "unit": "Rs",
        "rate": 826,
        "cost": 1561140,
        "costPerBua": 2.54,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      }
    ],
    "totalCost": 14161770,
    "totalCostPerBua": 23.03
  },
  {
    "id": "cat-16",
    "categoryName": "Security & Surveillance",
    "categoryCode": "SECURITY_AND_SU",
    "items": [
      {
        "id": "cp-item-143",
        "srNo": "1",
        "category": "Security & Surveillance",
        "item": "Camera & DVR",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "Rs",
        "rate": 676500,
        "cost": 676500,
        "costPerBua": 1.1,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 676500,
    "totalCostPerBua": 1.1
  },
  {
    "id": "cat-17",
    "categoryName": "Elevators",
    "categoryCode": "ELEVATORS",
    "items": [
      {
        "id": "cp-item-144",
        "srNo": "1",
        "category": "Elevators",
        "item": "Lifts",
        "qtyRcc": null,
        "qtyFinishes": 12,
        "qtyInfra": null,
        "qtyTotal": 12,
        "unit": "Nos.",
        "rate": 3186000,
        "cost": 38232000,
        "costPerBua": 62.17,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 38232000,
    "totalCostPerBua": 62.17
  },
  {
    "id": "cat-18",
    "categoryName": "Fire Fighting",
    "categoryCode": "FIRE_FIGHTING",
    "items": [
      {
        "id": "cp-item-145",
        "srNo": "1",
        "category": "Fire Fighting",
        "item": "All Building Fire Fighting (Material + Labour)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 20650000,
        "cost": 20650000,
        "costPerBua": 33.58,
        "scopeTag": "site_infra",
        "itemType": "labour"
      }
    ],
    "totalCost": 20650000,
    "totalCostPerBua": 33.58
  },
  {
    "id": "cat-19",
    "categoryName": "Aluminum Section Work",
    "categoryCode": "ALUMINUM_SECTIO",
    "items": [
      {
        "id": "cp-item-146",
        "srNo": "1",
        "category": "Aluminum Section Work",
        "item": "All Building Window Sections (Material + Labour)",
        "qtyRcc": null,
        "qtyFinishes": 79941.89,
        "qtyInfra": null,
        "qtyTotal": 79941.89,
        "unit": "Sqft",
        "rate": 472,
        "cost": 37732573,
        "costPerBua": 61.35,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-147",
        "srNo": "2",
        "category": "Aluminum Section Work",
        "item": "Glass Glazing on Penthouse Living Side Balconey Window Section",
        "qtyRcc": null,
        "qtyFinishes": 7295.19,
        "qtyInfra": null,
        "qtyTotal": 7295.19,
        "unit": "Sqft",
        "rate": 914.5,
        "cost": 6671454,
        "costPerBua": 10.85,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 44404027,
    "totalCostPerBua": 72.2
  },
  {
    "id": "cat-20",
    "categoryName": "Road & Other Works",
    "categoryCode": "ROAD_AND_OTHER_",
    "items": [
      {
        "id": "cp-item-148",
        "srNo": "1",
        "category": "Road & Other Works",
        "item": "Trimix Work Lower Basement-Labour",
        "qtyRcc": null,
        "qtyFinishes": 57318.3,
        "qtyInfra": null,
        "qtyTotal": 57318.3,
        "unit": "Sqft",
        "rate": 38.94,
        "cost": 2231975,
        "costPerBua": 3.63,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-149",
        "srNo": "2",
        "category": "Road & Other Works",
        "item": "Trimix Work Upper Basement-Labour",
        "qtyRcc": null,
        "qtyFinishes": 57318.3,
        "qtyInfra": null,
        "qtyTotal": 57318.3,
        "unit": "Sqft",
        "rate": 76.7,
        "cost": 4396314,
        "costPerBua": 7.15,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-150",
        "srNo": "3",
        "category": "Road & Other Works",
        "item": "Trimix Road Work (Labour + Material)-Ground Floor",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 28427.72,
        "qtyTotal": 28427.72,
        "unit": "Sqft",
        "rate": 135.7,
        "cost": 3857642,
        "costPerBua": 6.27,
        "scopeTag": "site_infra",
        "itemType": "labour"
      },
      {
        "id": "cp-item-151",
        "srNo": "4",
        "category": "Road & Other Works",
        "item": "Depart Labour-Road Cleaning-Motor Shifting-Dewatering-Amenities Cleaning-Flat Cleaning",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 4000000,
        "cost": 4000000,
        "costPerBua": 6.5,
        "scopeTag": "site_infra",
        "itemType": "labour"
      }
    ],
    "totalCost": 14485931,
    "totalCostPerBua": 23.55
  },
  {
    "id": "cat-21",
    "categoryName": "Amenities Interior Work",
    "categoryCode": "AMENITIES_INTER",
    "items": [
      {
        "id": "cp-item-152",
        "srNo": "1",
        "category": "Amenities Interior Work",
        "item": "Gym",
        "qtyRcc": null,
        "qtyFinishes": 3028.34,
        "qtyInfra": null,
        "qtyTotal": 3028.34,
        "unit": "Sqft",
        "rate": 2000,
        "cost": 6056688,
        "costPerBua": 9.85,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-153",
        "srNo": "2",
        "category": "Amenities Interior Work",
        "item": "Indoor Games",
        "qtyRcc": null,
        "qtyFinishes": 1739.03,
        "qtyInfra": null,
        "qtyTotal": 1739.03,
        "unit": "Sqft",
        "rate": 1750,
        "cost": 3043306,
        "costPerBua": 4.95,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-154",
        "srNo": "3",
        "category": "Amenities Interior Work",
        "item": "Toddler Play",
        "qtyRcc": null,
        "qtyFinishes": 1752.38,
        "qtyInfra": null,
        "qtyTotal": 1752.38,
        "unit": "Sqft",
        "rate": 2000,
        "cost": 3504758,
        "costPerBua": 5.7,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-155",
        "srNo": "4",
        "category": "Amenities Interior Work",
        "item": "Yoga/Aerobics/Zumba",
        "qtyRcc": null,
        "qtyFinishes": 985.98,
        "qtyInfra": null,
        "qtyTotal": 985.98,
        "unit": "Sqft",
        "rate": 1750,
        "cost": 1725469,
        "costPerBua": 2.81,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-156",
        "srNo": "5",
        "category": "Amenities Interior Work",
        "item": "Social Club",
        "qtyRcc": null,
        "qtyFinishes": 987.6,
        "qtyInfra": null,
        "qtyTotal": 987.6,
        "unit": "Sqft",
        "rate": 1750,
        "cost": 1728295,
        "costPerBua": 2.81,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-157",
        "srNo": "6",
        "category": "Amenities Interior Work",
        "item": "Banquet Hall",
        "qtyRcc": null,
        "qtyFinishes": 2800.58,
        "qtyInfra": null,
        "qtyTotal": 2800.58,
        "unit": "Sqft",
        "rate": 2500,
        "cost": 7001444,
        "costPerBua": 11.38,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-158",
        "srNo": "7",
        "category": "Amenities Interior Work",
        "item": "Male and Female Toilet",
        "qtyRcc": null,
        "qtyFinishes": 707.52,
        "qtyInfra": null,
        "qtyTotal": 707.52,
        "unit": "Sqft",
        "rate": 1500,
        "cost": 1061277,
        "costPerBua": 1.73,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-159",
        "srNo": "8",
        "category": "Amenities Interior Work",
        "item": "Multi Purpose Work",
        "qtyRcc": null,
        "qtyFinishes": 1293.62,
        "qtyInfra": null,
        "qtyTotal": 1293.62,
        "unit": "Sqft",
        "rate": 1500,
        "cost": 1940426,
        "costPerBua": 3.16,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-160",
        "srNo": "9",
        "category": "Amenities Interior Work",
        "item": "Steam and Jacuzzi",
        "qtyRcc": null,
        "qtyFinishes": 562.53,
        "qtyInfra": null,
        "qtyTotal": 562.53,
        "unit": "Sqft",
        "rate": 1500,
        "cost": 843790,
        "costPerBua": 1.37,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-161",
        "srNo": "10",
        "category": "Amenities Interior Work",
        "item": "Foyer Area All Buildings",
        "qtyRcc": null,
        "qtyFinishes": 2942.02,
        "qtyInfra": null,
        "qtyTotal": 2942.02,
        "unit": "Sqft",
        "rate": 2750,
        "cost": 8090545,
        "costPerBua": 13.16,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-162",
        "srNo": "11",
        "category": "Amenities Interior Work",
        "item": "Security Cabin",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 50,
        "qtyTotal": 50,
        "unit": "Sqft",
        "rate": 2000,
        "cost": 100000,
        "costPerBua": 0.16,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-163",
        "srNo": "12",
        "category": "Amenities Interior Work",
        "item": "Meter Room",
        "qtyRcc": null,
        "qtyFinishes": 742.72,
        "qtyInfra": null,
        "qtyTotal": 742.72,
        "unit": "Sqft",
        "rate": 1250,
        "cost": 928395,
        "costPerBua": 1.51,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-164",
        "srNo": "13",
        "category": "Amenities Interior Work",
        "item": "ODU Space Room",
        "qtyRcc": null,
        "qtyFinishes": 145.64,
        "qtyInfra": null,
        "qtyTotal": 145.64,
        "unit": "Sqft",
        "rate": 1500,
        "cost": 218455,
        "costPerBua": 0.36,
        "scopeTag": "building_finishes",
        "itemType": "material"
      },
      {
        "id": "cp-item-165",
        "srNo": "14",
        "category": "Amenities Interior Work",
        "item": "Society Office",
        "qtyRcc": null,
        "qtyFinishes": 403.76,
        "qtyInfra": null,
        "qtyTotal": 403.76,
        "unit": "Sqft",
        "rate": 1500,
        "cost": 605636,
        "costPerBua": 0.98,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 36848484,
    "totalCostPerBua": 59.93
  },
  {
    "id": "cat-22",
    "categoryName": "Landscape & Hardscape",
    "categoryCode": "LANDSCAPE_AND_H",
    "items": [
      {
        "id": "cp-item-166",
        "srNo": "1",
        "category": "Landscape & Hardscape",
        "item": "Party Lawn (Mat + Lab)",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 7104.24,
        "qtyTotal": 7104.24,
        "unit": "Sqft",
        "rate": 100,
        "cost": 710424,
        "costPerBua": 1.16,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-167",
        "srNo": "2",
        "category": "Landscape & Hardscape",
        "item": "Children's Play Area",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 2223.52,
        "qtyTotal": 2223.52,
        "unit": "Sqft",
        "rate": 650,
        "cost": 1445288,
        "costPerBua": 2.35,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-168",
        "srNo": "3",
        "category": "Landscape & Hardscape",
        "item": "Skating Area",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 550.69,
        "qtyTotal": 550.69,
        "unit": "Sqft",
        "rate": 450,
        "cost": 247809,
        "costPerBua": 0.4,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-169",
        "srNo": "4",
        "category": "Landscape & Hardscape",
        "item": "Multi Sport Court Area",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 2245.05,
        "qtyTotal": 2245.05,
        "unit": "Sqft",
        "rate": 500,
        "cost": 1157524,
        "costPerBua": 1.88,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-170",
        "srNo": "5",
        "category": "Landscape & Hardscape",
        "item": "Netcricket",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 554.13,
        "qtyTotal": 554.13,
        "unit": "Sqft",
        "rate": 550,
        "cost": 304772,
        "costPerBua": 0.5,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-171",
        "srNo": "6",
        "category": "Landscape & Hardscape",
        "item": "Amphitheater",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 330.99,
        "qtyTotal": 330.99,
        "unit": "Sqft",
        "rate": 850,
        "cost": 281344,
        "costPerBua": 0.46,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-172",
        "srNo": "7",
        "category": "Landscape & Hardscape",
        "item": "Outdoor Exercise",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 660.26,
        "qtyTotal": 660.26,
        "unit": "Sqft",
        "rate": 450,
        "cost": 297119,
        "costPerBua": 0.48,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-173",
        "srNo": "8",
        "category": "Landscape & Hardscape",
        "item": "Outdoor Activity",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 498.91,
        "qtyTotal": 498.91,
        "unit": "Sqft",
        "rate": 450,
        "cost": 224510,
        "costPerBua": 0.37,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-174",
        "srNo": "9",
        "category": "Landscape & Hardscape",
        "item": "Building Lobby",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 2001.14,
        "qtyTotal": 2001.14,
        "unit": "Sqft",
        "rate": 235,
        "cost": 470267,
        "costPerBua": 0.76,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-175",
        "srNo": "10",
        "category": "Landscape & Hardscape",
        "item": "Tuck-in seatings with lawn",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 624.31,
        "qtyTotal": 624.31,
        "unit": "Sqft",
        "rate": 350,
        "cost": 218509,
        "costPerBua": 0.36,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-176",
        "srNo": "11",
        "category": "Landscape & Hardscape",
        "item": "Gazebo Outdoor Seating",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 322.92,
        "qtyTotal": 322.92,
        "unit": "Sqft",
        "rate": 450,
        "cost": 145314,
        "costPerBua": 0.24,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-177",
        "srNo": "12",
        "category": "Landscape & Hardscape",
        "item": "Seat Out Area in Lawn",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1009.34,
        "qtyTotal": 1009.34,
        "unit": "Sqft",
        "rate": 600,
        "cost": 605604,
        "costPerBua": 0.98,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-178",
        "srNo": "13",
        "category": "Landscape & Hardscape",
        "item": "Plantations/Trees/Shrubs",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 2240000,
        "cost": 2240000,
        "costPerBua": 3.64,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-179",
        "srNo": "14",
        "category": "Landscape & Hardscape",
        "item": "Open Plaza/Tree Plaza",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 2153.98,
        "qtyTotal": 2153.98,
        "unit": "Sqft",
        "rate": 450,
        "cost": 969293,
        "costPerBua": 1.58,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-180",
        "srNo": "15",
        "category": "Landscape & Hardscape",
        "item": "1st Floor Pathway/Track",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 3982.68,
        "qtyTotal": 3982.68,
        "unit": "Sqft",
        "rate": 450,
        "cost": 1792206,
        "costPerBua": 2.91,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-181",
        "srNo": "16",
        "category": "Landscape & Hardscape",
        "item": "Ramp",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1419.88,
        "qtyTotal": 1419.88,
        "unit": "Sqft",
        "rate": 650,
        "cost": 922922,
        "costPerBua": 1.5,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-182",
        "srNo": "17",
        "category": "Landscape & Hardscape",
        "item": "Elevated Deck",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 247.57,
        "qtyTotal": 247.57,
        "unit": "Sqft",
        "rate": 450,
        "cost": 111407,
        "costPerBua": 0.18,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-183",
        "srNo": "18",
        "category": "Landscape & Hardscape",
        "item": "Water Body",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 387.5,
        "qtyTotal": 387.5,
        "unit": "Sqft",
        "rate": 450,
        "cost": 474377,
        "costPerBua": 0.77,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-184",
        "srNo": "19",
        "category": "Landscape & Hardscape",
        "item": "Swing Plaza",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 306.67,
        "qtyTotal": 306.67,
        "unit": "Sqft",
        "rate": 450,
        "cost": 138000,
        "costPerBua": 0.22,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-185",
        "srNo": "20",
        "category": "Landscape & Hardscape",
        "item": "Drain Cell",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 9795.24,
        "qtyTotal": 9795.24,
        "unit": "Sq.ft",
        "rate": 44.84,
        "cost": 439219,
        "costPerBua": 0.71,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-186",
        "srNo": "21",
        "category": "Landscape & Hardscape",
        "item": "Geo Membrane",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 12830.69,
        "qtyTotal": 12830.69,
        "unit": "Sq.ft",
        "rate": 17.7,
        "cost": 227103,
        "costPerBua": 0.37,
        "scopeTag": "site_infra",
        "itemType": "material"
      },
      {
        "id": "cp-item-187",
        "srNo": "22",
        "category": "Landscape & Hardscape",
        "item": "Light Weight Filling Material",
        "qtyRcc": null,
        "qtyFinishes": null,
        "qtyInfra": 1,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 1000000,
        "cost": 1000000,
        "costPerBua": 1.63,
        "scopeTag": "site_infra",
        "itemType": "material"
      }
    ],
    "totalCost": 14423011,
    "totalCostPerBua": 23.45
  },
  {
    "id": "cat-23",
    "categoryName": "Signages",
    "categoryCode": "SIGNAGES",
    "items": [
      {
        "id": "cp-item-188",
        "srNo": "1",
        "category": "Signages",
        "item": "Signages",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 2000000,
        "cost": 2000000,
        "costPerBua": 3.25,
        "scopeTag": "building_finishes",
        "itemType": "material"
      }
    ],
    "totalCost": 2000000,
    "totalCostPerBua": 3.25
  },
  {
    "id": "cat-24",
    "categoryName": "Compound Wall and Entrance Gate",
    "categoryCode": "COMPOUND_WALL_A",
    "items": [
      {
        "id": "cp-item-189",
        "srNo": "1",
        "category": "Compound Wall and Entrance Gate",
        "item": "Main Entrance Gate (Civil + Finishing Work)",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 6500000,
        "cost": 6500000,
        "costPerBua": 10.57,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-190",
        "srNo": "2",
        "category": "Compound Wall and Entrance Gate",
        "item": "Compound Wall (Civil + Finishing Work)",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 5000000,
        "cost": 5000000,
        "costPerBua": 8.13,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      },
      {
        "id": "cp-item-191",
        "srNo": "3",
        "category": "Compound Wall and Entrance Gate",
        "item": "Planters & Sitting Pods (Civil Work)",
        "qtyRcc": null,
        "qtyFinishes": 1,
        "qtyInfra": null,
        "qtyTotal": 1,
        "unit": "LS",
        "rate": 6000000,
        "cost": 6000000,
        "costPerBua": 9.76,
        "scopeTag": "building_finishes",
        "itemType": "labour"
      }
    ],
    "totalCost": 17500000,
    "totalCostPerBua": 28.46
  }
];
