// ============================================================================
// PRAMUKH GROUP ERP V2 — MEASUREMENT BOOK
// File: frontend/src/lib/measurement-sheets.ts
//
// Site-recorded quantities that justify an RA bill. A VERIFIED sheet is a hard
// prerequisite for certifying a service bill (trg_service_bill_evidence_gate),
// unless the project sets budget_config.sb_measurement_enforcement = warn_only.
//
// Quantities are never computed here: measurement_sheet_items.total_quantity is
// a generated column (nos x L x W x H - deduction, floored at zero) and the
// sheet header rolls up from a trigger. The figures shown in the UI are a
// preview of what the server will store, never an independent calculation.
// ============================================================================

import { supabase, getDbSiteId } from '@/utils/supabase-client';
import { isLiveSupabase } from '@/lib/erp/supabase-modules';

type MutationResult<T = unknown> = { data: T | null; error: Error | null };

function asError(error: unknown): Error {
  return error instanceof Error ? error : new Error(String(error));
}

/** Guard messages are written for the person reading the screen. */
function asDbError(error: { message?: string; code?: string; hint?: string | null } | null): Error {
  if (!error) return new Error('Unknown database error.');
  const message = error.message || 'The database rejected this change.';
  if (error.hint && (error.code === '22023' || error.code === '23514')) {
    return new Error(`${message} ${error.hint}`);
  }
  return new Error(message);
}

export type MeasurementSheetStatus = 'draft' | 'submitted' | 'verified' | 'rejected';

export type MeasurementSheetItemRow = {
  id: string;
  measurement_sheet_id: string;
  work_order_line_id: string | null;
  description: string;
  unit: string | null;
  nos: number;
  length: number;
  width: number;
  height_depth: number;
  deduction: number;
  /** Generated by the database. Read-only. */
  total_quantity: number;
  remarks: string | null;
  sort_order: number;
};

export type MeasurementSheetRow = {
  id: string;
  project_id: string;
  work_order_id: string;
  activity_id: string | null;
  sheet_number: string;
  measurement_date: string;
  period_start_date: string | null;
  period_end_date: string | null;
  location_reference: string | null;
  remarks: string | null;
  status: MeasurementSheetStatus;
  prepared_by: string | null;
  prepared_at: string | null;
  verified_by: string | null;
  verified_at: string | null;
  rejected_by: string | null;
  rejected_at: string | null;
  rejection_reason: string | null;
  total_quantity: number;
  created_at: string;
  work_orders?: { id: string; work_order_number: string | null; wo_status: string } | null;
  measurement_sheet_items?: MeasurementSheetItemRow[];
};

const SHEET_SELECT =
  '*, work_orders(id, work_order_number, wo_status)';

/** Legal Measurement Book moves. Mirrors ms_transition_allowed(). */
const MS_TRANSITIONS: Record<MeasurementSheetStatus, MeasurementSheetStatus[]> = {
  draft: ['submitted'],
  submitted: ['verified', 'rejected', 'draft'],
  // A verified sheet can only be pulled back to submitted, and the database
  // refuses even that once a certified bill relies on it.
  verified: ['submitted'],
  rejected: ['draft', 'submitted'],
};

export function nextMeasurementSheetStatuses(
  current: string | null | undefined,
  canVerify: boolean,
): MeasurementSheetStatus[] {
  const key = (current ?? '').trim().toLowerCase() as MeasurementSheetStatus;
  const options = MS_TRANSITIONS[key] ?? [];
  return options.filter((next) => canVerify || (next !== 'verified' && next !== 'rejected'));
}

export const MEASUREMENT_SHEET_STATUS_LABELS: Record<MeasurementSheetStatus, string> = {
  draft: 'Draft',
  submitted: 'Submitted',
  verified: 'Verified',
  rejected: 'Rejected',
};

export const MEASUREMENT_SHEET_ACTION_LABELS: Record<MeasurementSheetStatus, string> = {
  draft: 'Return to Draft',
  submitted: 'Submit for Verification',
  verified: 'Verify Measurement',
  rejected: 'Reject',
};

/** Sheets for a Work Order, newest first. */
export async function listMeasurementSheets(workOrderId: string): Promise<MeasurementSheetRow[]> {
  if (!isLiveSupabase() || !workOrderId) return [];

  const { data, error } = await supabase
    .from('measurement_sheets')
    .select(SHEET_SELECT)
    .eq('work_order_id', workOrderId)
    .is('deleted_at', null)
    .order('measurement_date', { ascending: false })
    .order('created_at', { ascending: false });

  if (error) throw asDbError(error);
  return (data ?? []) as unknown as MeasurementSheetRow[];
}

/** Verified sheets only — what a bill may legally be built from. */
export async function listVerifiedMeasurementSheets(
  workOrderId: string,
): Promise<MeasurementSheetRow[]> {
  if (!isLiveSupabase() || !workOrderId) return [];

  const { data, error } = await supabase
    .from('measurement_sheets')
    .select(SHEET_SELECT)
    .eq('work_order_id', workOrderId)
    .eq('status', 'verified')
    .is('deleted_at', null)
    .order('measurement_date', { ascending: false });

  if (error) throw asDbError(error);
  return (data ?? []) as unknown as MeasurementSheetRow[];
}

export async function getMeasurementSheet(sheetId: string): Promise<MeasurementSheetRow | null> {
  if (!isLiveSupabase() || !sheetId) return null;

  const { data, error } = await supabase
    .from('measurement_sheets')
    .select(`${SHEET_SELECT}, measurement_sheet_items(*)`)
    .eq('id', sheetId)
    .is('deleted_at', null)
    .maybeSingle();

  if (error) throw asDbError(error);
  return (data as unknown as MeasurementSheetRow) ?? null;
}

export type CreateMeasurementItemInput = {
  description: string;
  unit?: string;
  nos?: number;
  length?: number;
  width?: number;
  heightDepth?: number;
  deduction?: number;
  workOrderLineId?: string;
  /**
   * The unit of claim being measured. A line with one claim resolves through
   * work_order_line_id, but a stage-billed line has one claim per stage and an
   * unattributed sheet cannot be apportioned between them.
   */
  billableItemId?: string;
  remarks?: string;
};

export type CreateMeasurementSheetInput = {
  projectId: string;
  workOrderId: string;
  activityId?: string;
  sheetNumber: string;
  measurementDate: string;
  periodStartDate?: string;
  periodEndDate?: string;
  locationReference?: string;
  remarks?: string;
  items: CreateMeasurementItemInput[];
};

/**
 * Record a Measurement Book sheet. Created as draft; the site engineer submits
 * it and a verifier signs it off before any bill can rely on it.
 */
export async function createMeasurementSheet(
  input: CreateMeasurementSheetInput,
): Promise<MutationResult<{ id: string }>> {
  try {
    if (!isLiveSupabase()) throw new Error('Supabase is not configured.');
    if (!input.workOrderId) throw new Error('A Work Order is required.');
    if (!input.sheetNumber?.trim()) throw new Error('A sheet number is required.');

    const items = input.items.filter((item) => item.description.trim());
    if (items.length === 0) {
      throw new Error('A measurement sheet needs at least one measured item.');
    }

    const dbProjectId = getDbSiteId(input.projectId);

    const { data, error } = await supabase
      .from('measurement_sheets')
      .insert({
        project_id: dbProjectId,
        work_order_id: input.workOrderId,
        activity_id: input.activityId || null,
        sheet_number: input.sheetNumber.trim(),
        measurement_date: input.measurementDate,
        period_start_date: input.periodStartDate || null,
        period_end_date: input.periodEndDate || null,
        location_reference: input.locationReference || null,
        remarks: input.remarks || null,
        status: 'draft',
      })
      .select('id')
      .single();

    if (error) throw asDbError(error);
    const sheetId = (data as { id: string }).id;

    const itemRows = items.map((item, index) => ({
      measurement_sheet_id: sheetId,
      project_id: dbProjectId,
      work_order_line_id: item.workOrderLineId || null,
      billable_item_id: item.billableItemId || null,
      description: item.description.trim(),
      unit: item.unit || null,
      nos: item.nos ?? 1,
      length: item.length ?? 1,
      width: item.width ?? 1,
      height_depth: item.heightDepth ?? 1,
      deduction: item.deduction ?? 0,
      remarks: item.remarks || null,
      sort_order: index,
      // total_quantity is generated — deliberately not sent.
    }));

    const { error: itemError } = await supabase.from('measurement_sheet_items').insert(itemRows);
    if (itemError) {
      // Never strand an empty sheet: it would read as a nil measurement and
      // could not be submitted anyway (the guard requires items).
      await supabase.from('measurement_sheets').delete().eq('id', sheetId);
      throw asDbError(itemError);
    }

    return { data: { id: sheetId }, error: null };
  } catch (error) {
    return { data: null, error: asError(error) };
  }
}

/**
 * Every Measurement Book transition. Routes through
 * set_measurement_sheet_status(), which validates the move, requires items to
 * submit or verify, refuses to un-verify a sheet that supports a certified
 * bill, and stamps the actor server-side.
 */
export async function setMeasurementSheetStatus(
  sheetId: string,
  newStatus: MeasurementSheetStatus,
  reason?: string,
): Promise<MutationResult<{ id: string; status: MeasurementSheetStatus; totalQuantity: number }>> {
  try {
    if (!isLiveSupabase()) throw new Error('Supabase is not configured.');
    if (newStatus === 'rejected' && !reason?.trim()) {
      throw new Error('A rejection reason is mandatory.');
    }

    const { data, error } = await supabase.rpc('set_measurement_sheet_status', {
      p_sheet_id: sheetId,
      p_status: newStatus,
      p_reason: reason?.trim() || null,
    });

    if (error) throw asDbError(error);

    const row = (data ?? {}) as Record<string, unknown>;
    return {
      data: {
        id: (row.id as string) ?? sheetId,
        status: (row.status as MeasurementSheetStatus) ?? newStatus,
        totalQuantity: Number(row.total_quantity || 0),
      },
      error: null,
    };
  } catch (error) {
    return { data: null, error: asError(error) };
  }
}

/** Per Work Order line: contracted, certified, remaining and measured. */
export type WorkOrderLineBillingPosition = {
  workOrderLineId: string;
  description: string;
  unit: string | null;
  contractedQuantity: number;
  rate: number;
  certifiedQuantity: number;
  remainingQuantity: number;
  measuredQuantity: number;
};

/**
 * The derived cumulative that makes SEQUENTIAL RA entry safe.
 *
 * All 153 parsed certificates bill newly completed scope at 100% and never
 * carry a "previous quantity" column, so the user types this bill only. The
 * cumulative is computed server-side and enforced by
 * trg_sb_over_measurement_guard — the same control a cumulative-entry form
 * would give, without changing how anyone bills.
 */
export async function getWorkOrderLineBillingPosition(
  workOrderId: string,
): Promise<WorkOrderLineBillingPosition[]> {
  if (!isLiveSupabase() || !workOrderId) return [];

  const { data, error } = await supabase.rpc('rpc_wo_line_billing_position', {
    p_work_order_id: workOrderId,
  });

  if (error) throw asDbError(error);

  return ((data ?? []) as Record<string, unknown>[]).map((row) => ({
    workOrderLineId: row.work_order_line_id as string,
    description: (row.description as string) ?? '',
    unit: (row.unit as string) ?? null,
    contractedQuantity: Number(row.contracted_quantity || 0),
    rate: Number(row.rate || 0),
    certifiedQuantity: Number(row.certified_quantity || 0),
    remainingQuantity: Number(row.remaining_quantity || 0),
    measuredQuantity: Number(row.measured_quantity || 0),
  }));
}

/**
 * Whether this project blocks certification without a verified measurement.
 * Mirrors budget_config.sb_measurement_enforcement so the bill form can warn up
 * front instead of letting the database reject the certify action.
 */
export async function isMeasurementRequiredForCertification(projectId: string): Promise<boolean> {
  if (!isLiveSupabase() || !projectId) return true;

  const { data, error } = await supabase
    .from('budget_config')
    .select('sb_measurement_enforcement')
    .eq('project_id', getDbSiteId(projectId))
    .maybeSingle();

  // Default to the strict reading: the database default is 'block'.
  if (error || !data) return true;
  return (data.sb_measurement_enforcement ?? 'block') === 'block';
}
