export interface Orbit3VarianceItem {
  id: string;
  srNo: string;
  parentGroup?: string;
  subGroup?: string;
  headActivity?: string;
  subActivity: string;
  workStatus?: string;
  unit: string;
  budgetQty: number;
  budgetRate: number;
  budgetCost: number;
  poQty?: number;
  poRate?: number;
  poAmount?: number;
  actualBillQty: number;
  actualBillRate: number;
  actualTotalCost: number;
  qtyVariation: number;
  rateVariation: number;
  balance: number;
  costVarianceAmount: number;
  costVariancePercent: number;
  remark: string;
}

export interface Orbit3VarianceCategory {
  id: string;
  categoryName: string;
  items: Orbit3VarianceItem[];
  totalBudgetCost: number;
  totalActualCost: number;
  totalBalance: number;
  totalVarianceAmount: number;
}

export const ORBIT3_VARIANCE_CATEGORIES: Orbit3VarianceCategory[] = [
  {
    "id": "var-cat-1",
    "categoryName": "Site Development / Pre Construction Works",
    "items": [
      {
        "id": "orbit3-var-1",
        "srNo": "1",
        "parentGroup": "Civil Work",
        "subGroup": "Site Preparation and Ground work",
        "headActivity": "Site Development / Pre Construction Works",
        "subActivity": "Site Development / Pre Construction / Hoardings Works",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 1955501,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -1955501,
        "costVariancePercent": 0,
        "remark": "Non budgeted cost - Fabrication Work for sloping roof shade, Hoardings etc. "
      }
    ],
    "totalBudgetCost": 0,
    "totalActualCost": 1955501,
    "totalBalance": 0,
    "totalVarianceAmount": -1955501
  },
  {
    "id": "var-cat-2",
    "categoryName": "Excavation/Backfilling and D-Wall Works",
    "items": [
      {
        "id": "orbit3-var-2",
        "srNo": "1",
        "parentGroup": "Civil Work",
        "subGroup": "Site Preparation and Ground work",
        "headActivity": "Excavation/Backfilling and D-Wall Works",
        "subActivity": "Excavation/Backfilling",
        "workStatus": "Not Completed",
        "unit": "Lum",
        "budgetQty": 1.0,
        "budgetRate": 1350000.0,
        "budgetCost": 1350000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 1864802,
        "qtyVariation": -1.0,
        "rateVariation": -1350000.0,
        "balance": 0,
        "costVarianceAmount": -514802,
        "costVariancePercent": -38.13,
        "remark": "challenges in excavation due to unpredictable site condition."
      },
      {
        "id": "orbit3-var-3",
        "srNo": "2",
        "parentGroup": "Civil Work",
        "subGroup": "Site Preparation and Ground work",
        "headActivity": "Excavation/Backfilling and D-Wall Works",
        "subActivity": "D-Wall",
        "workStatus": "Not Completed",
        "unit": "Lum",
        "budgetQty": 1.0,
        "budgetRate": 13500000.0,
        "budgetCost": 13500000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 26000346,
        "qtyVariation": -1.0,
        "rateVariation": -13500000.0,
        "balance": 0,
        "costVarianceAmount": -12500346,
        "costVariancePercent": -92.6,
        "remark": "one side wall was not planned initially which later was constructed as per site condition. Increase in Anchoring and Unfavourable pit condition was also a reason for escalation. "
      },
      {
        "id": "orbit3-var-4",
        "srNo": "3",
        "parentGroup": "Civil Work",
        "subGroup": "Site Preparation and Ground work",
        "headActivity": "Excavation/Backfilling and D-Wall Works",
        "subActivity": "Rubble work",
        "workStatus": "Not Completed",
        "unit": "Tonn",
        "budgetQty": 1500.0,
        "budgetRate": 625.0,
        "budgetCost": 937500,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 2079993,
        "qtyVariation": -1500.0,
        "rateVariation": -625.0,
        "balance": 0,
        "costVarianceAmount": -1142493,
        "costVariancePercent": -121.87,
        "remark": "extensive amount was used to make road or working base in muddy excavation pit to create working condition."
      }
    ],
    "totalBudgetCost": 15787500,
    "totalActualCost": 29945141,
    "totalBalance": 0,
    "totalVarianceAmount": -14157641
  },
  {
    "id": "var-cat-3",
    "categoryName": "Civil and Misc Work",
    "items": [
      {
        "id": "orbit3-var-5",
        "srNo": "1",
        "parentGroup": "Civil Work",
        "subGroup": "Civil -Rcc/Mas./Plast work",
        "headActivity": "Civil -Rcc/Mas./Plast work",
        "subActivity": "Civil Labour Cost",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 225000.0,
        "budgetRate": 826.0,
        "budgetCost": 185850000,
        "poQty": 225000.0,
        "poRate": 826.0,
        "poAmount": 185850000,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 146499660,
        "qtyVariation": 0.0,
        "rateVariation": 0.0,
        "balance": 39350340,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-6",
        "srNo": "2",
        "parentGroup": "Civil Work",
        "subGroup": "Material rate diff. & other work",
        "headActivity": "Material rate diff. & other work",
        "subActivity": "PT Cost",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 2596000.0,
        "budgetCost": 2596000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 728966,
        "qtyVariation": -1.0,
        "rateVariation": -2596000.0,
        "balance": 1867034,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-7",
        "srNo": "3",
        "parentGroup": "Civil Work",
        "subGroup": "Material rate diff. & other work",
        "headActivity": "Material rate diff. & other work",
        "subActivity": "Rebar Work",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 486705,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -486705,
        "costVariancePercent": 0,
        "remark": "Non budgeted cost."
      },
      {
        "id": "orbit3-var-8",
        "srNo": "4",
        "parentGroup": "Civil Work",
        "subGroup": "Material rate diff. & other work",
        "headActivity": "Material rate diff. & other work",
        "subActivity": "Misc. Civil & SMC Rule Exp",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 329380,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -329380,
        "costVariancePercent": 0,
        "remark": "Non budgeted cost. (Tarpaulin, fire eqi, civil work, etc.)"
      },
      {
        "id": "orbit3-var-9",
        "srNo": "5",
        "parentGroup": "Civil Work",
        "subGroup": "Material rate diff. & other work",
        "headActivity": "Material rate diff. & other work",
        "subActivity": "Rate Difference @ 12%",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 225000.0,
        "budgetRate": 99.12,
        "budgetCost": 22302000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -225000.0,
        "rateVariation": -99.12,
        "balance": 22302000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 210748000,
    "totalActualCost": 148044711,
    "totalBalance": 63519374,
    "totalVarianceAmount": -816085
  },
  {
    "id": "var-cat-4",
    "categoryName": "Civil Materials",
    "items": [
      {
        "id": "orbit3-var-10",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Civil Materials",
        "headActivity": "Civil Materials",
        "subActivity": "Cement-Flooring, Dado, Frame, Trimix & Water Proofing Work",
        "workStatus": "Not Completed",
        "unit": "Bags",
        "budgetQty": 13130.17,
        "budgetRate": 385.0,
        "budgetCost": 5055115,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 85502,
        "qtyVariation": -13130.17,
        "rateVariation": -385.0,
        "balance": 4969614,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-11",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Civil Materials",
        "headActivity": "Civil Materials",
        "subActivity": "Sand",
        "workStatus": "Not Completed",
        "unit": "Ton",
        "budgetQty": 2278.91,
        "budgetRate": 1250.0,
        "budgetCost": 2848639,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2278.91,
        "rateVariation": -1250.0,
        "balance": 2848639,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-12",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Civil Materials",
        "headActivity": "Civil Materials",
        "subActivity": "Metal 10mm & 20mm",
        "workStatus": "Not Completed",
        "unit": "Ton",
        "budgetQty": 1377.99,
        "budgetRate": 1050.0,
        "budgetCost": 1446891,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 34317,
        "qtyVariation": -1377.99,
        "rateVariation": -1050.0,
        "balance": 1412574,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-13",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Civil Materials",
        "headActivity": "Civil Materials",
        "subActivity": "Bricks (Toilet + Terrace + Water Tanks + Balcony)",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 149709.21,
        "budgetRate": 10.03,
        "budgetCost": 1501583,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -149709.21,
        "rateVariation": -10.03,
        "balance": 1501583,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 10852228,
    "totalActualCost": 119819,
    "totalBalance": 10732410,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-5",
    "categoryName": "Waterproofing Work",
    "items": [
      {
        "id": "orbit3-var-14",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Waterproofing Work",
        "headActivity": "Waterproofing Work",
        "subActivity": "Water Proofing Chemical Labour + Material (Base Coat) (Toilet + Terrace + Water Tanks + Balcony)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 48453.81,
        "budgetRate": 76.7,
        "budgetCost": 3716407,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -48453.81,
        "rateVariation": -76.7,
        "balance": 3716407,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-15",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Waterproofing Work",
        "headActivity": "Waterproofing Work",
        "subActivity": "Water Proofing Brick Bat Labour (Toilet + Terrace + Water Tanks+Balcony)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 19022.28,
        "budgetRate": 28.32,
        "budgetCost": 538711,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -19022.28,
        "rateVariation": -28.32,
        "balance": 538711,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-16",
        "srNo": "8",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Waterproofing Work",
        "headActivity": "Waterproofing Work",
        "subActivity": "Water Proofing Basement Retaining Wall",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 28252.27,
        "budgetRate": 82.6,
        "budgetCost": 2333638,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 2308810,
        "qtyVariation": -28252.27,
        "rateVariation": -82.6,
        "balance": 24828,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-17",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Waterproofing Work",
        "headActivity": "Waterproofing Work",
        "subActivity": "GF. Floor Podium Water Proofing",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 17771.36,
        "budgetRate": 188.8,
        "budgetCost": 3355234,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -17771.36,
        "rateVariation": -188.8,
        "balance": 3355234,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 9943990,
    "totalActualCost": 2308810,
    "totalBalance": 7635180,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-6",
    "categoryName": "Stone and Tiles Materials",
    "items": [
      {
        "id": "orbit3-var-18",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Tiles 600 X 600 - Office, ODU, Toilet flooring and Dado Tiles Materials",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 131372.5,
        "budgetRate": 41.3,
        "budgetCost": 5425684,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -131372.5,
        "rateVariation": -41.3,
        "balance": 5425684,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-19",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Tiles 600 X 600 - Balcony Flooring  Tiles",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 4368.16,
        "budgetRate": 94.4,
        "budgetCost": 412354,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -4368.16,
        "rateVariation": -94.4,
        "balance": 412354,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-20",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Tiles 600 X 600 - Common Passage flooring and Dado Tiles",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 28421.88,
        "budgetRate": 64.9,
        "budgetCost": 1844580,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -28421.88,
        "rateVariation": -64.9,
        "balance": 1844580,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-21",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Tiles 1200 X 2400 - Gr. Floor Foyer Flooring and Dado Tiles",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2300.0,
        "budgetRate": 165.2,
        "budgetCost": 379960,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2300.0,
        "rateVariation": -165.2,
        "balance": 379960,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-22",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Granite - Door - Table top Basin Platform, Staircase",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 26554.81,
        "budgetRate": 100.3,
        "budgetCost": 2663447,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 5777.3,
        "actualBillRate": 60.0,
        "actualTotalCost": 346655,
        "qtyVariation": -20777.51,
        "rateVariation": -40.3,
        "balance": 2316792,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-23",
        "srNo": "6",
        "parentGroup": "",
        "subGroup": "#N/A",
        "headActivity": "#N/A",
        "subActivity": "Window frame",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 3727.54,
        "budgetRate": 100.3,
        "budgetCost": 373873,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 1022.67,
        "actualBillRate": 47.24,
        "actualTotalCost": 48308,
        "qtyVariation": -2704.87,
        "rateVariation": -53.06,
        "balance": 325565,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-24",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Granite - Lift Frame",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 1401.51,
        "budgetRate": 118.0,
        "budgetCost": 165378,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1401.51,
        "rateVariation": -118.0,
        "balance": 165378,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-25",
        "srNo": "8",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Terrace Flooring",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 7239.69,
        "budgetRate": 23.6,
        "budgetCost": 170857,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -7239.69,
        "rateVariation": -23.6,
        "balance": 170857,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-26",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Materials",
        "subActivity": "Misc. Stone and Tiles Materials",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 206936,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -206936,
        "costVariancePercent": 0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 11436133,
    "totalActualCost": 601899,
    "totalBalance": 11041170,
    "totalVarianceAmount": -206936
  },
  {
    "id": "var-cat-7",
    "categoryName": "Stone and Tiles Labour",
    "items": [
      {
        "id": "orbit3-var-27",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Labour",
        "subActivity": "Office/Showroom Flooring, & Dado, Toilet, Balcony, Frame and Platform Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 5163600.0,
        "budgetCost": 5163600,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 273401,
        "qtyVariation": -1.0,
        "rateVariation": -5163600.0,
        "balance": 4890199,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-28",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Labour",
        "subActivity": "ODU Space Flooring-600MM X 600MM Tiles Flooring Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 88839.94,
        "budgetCost": 88840,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -88839.94,
        "balance": 88840,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-29",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Labour",
        "subActivity": "Common Passage, Lift frame & Staircase flooring & Dado Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 3016579.84,
        "budgetCost": 3016580,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -3016579.84,
        "balance": 3016580,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-30",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Labour",
        "subActivity": "Gr. Floor Foyer Flooring & Dado labour (1200 X 2400 Tiles)",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 143107.42,
        "budgetCost": 143107,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -143107.42,
        "balance": 143107,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-31",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Stone and Tiles Work",
        "headActivity": "Stone and Tiles Labour",
        "subActivity": "Top Terrace flooring Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 321442.42,
        "budgetCost": 321442,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -321442.42,
        "balance": 321442,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 8733569,
    "totalActualCost": 273401,
    "totalBalance": 8460168,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-8",
    "categoryName": "Inernal Surface Finishes (Material + Labour)",
    "items": [
      {
        "id": "orbit3-var-32",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Office/Showroom Walls/Ceiling (Gypsum + Primer)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 258885.84,
        "budgetRate": 12.09,
        "budgetCost": 3131224,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -258885.84,
        "rateVariation": -12.09,
        "balance": 3131224,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-33",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Office/Showroom Walls/Ceiling (Primer Material)",
        "workStatus": "Not Completed",
        "unit": "Ltr.",
        "budgetQty": 6661.91,
        "budgetRate": 90.86,
        "budgetCost": 605301,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -6661.91,
        "rateVariation": -90.86,
        "balance": 605301,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-34",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Common Passage Walls (Texture + Paint)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 22497.42,
        "budgetRate": 53.1,
        "budgetCost": 1194613,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -22497.42,
        "rateVariation": -53.1,
        "balance": 1194613,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-35",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Stair case Passage Ceiling (Gypsum + Primer)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 7590.53,
        "budgetRate": 12.09,
        "budgetCost": 91807,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -7590.53,
        "rateVariation": -12.09,
        "balance": 91807,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-36",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Basement Wall+Column+Ceiling (Putty)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 84223.13,
        "budgetRate": 8.26,
        "budgetCost": 695683,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -84223.13,
        "rateVariation": -8.26,
        "balance": 695683,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-37",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Ramp Wall (Texture+Paint)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 6391.37,
        "budgetRate": 53.1,
        "budgetCost": 339382,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -6391.37,
        "rateVariation": -53.1,
        "balance": 339382,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-38",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Texture and Colour Work",
        "headActivity": "Inernal Surface Finishes (Material + Labour)",
        "subActivity": "Msic Texture and Colour Work",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": 0,
        "costVariancePercent": 0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 6058010,
    "totalActualCost": 0,
    "totalBalance": 6058010,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-9",
    "categoryName": "Door and Hardwares",
    "items": [
      {
        "id": "orbit3-var-39",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Door and Hardwares Work",
        "headActivity": "Door and Hardwares",
        "subActivity": "Laminate Door and Hardwares + Fitting-Office and Shop",
        "workStatus": "Not Completed",
        "unit": "Doors",
        "budgetQty": 122.0,
        "budgetRate": 4817.5,
        "budgetCost": 587735,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -122.0,
        "rateVariation": -4817.5,
        "balance": 587735,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-40",
        "srNo": "10",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Door and Hardwares Work",
        "headActivity": "Door and Hardwares",
        "subActivity": "Laminate Door and Hardwares + Fitting-Toilet",
        "workStatus": "Not Completed",
        "unit": "Doors",
        "budgetQty": 135.0,
        "budgetRate": 4705.0,
        "budgetCost": 635175,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -135.0,
        "rateVariation": -4705.0,
        "balance": 635175,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-41",
        "srNo": "11",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Door and Hardwares Work",
        "headActivity": "Door and Hardwares",
        "subActivity": "False Ceiling Passage Area",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 20783.22,
        "budgetRate": 100.3,
        "budgetCost": 2084557,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -20783.22,
        "rateVariation": -100.3,
        "balance": 2084557,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-42",
        "srNo": "12",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Door and Hardwares Work",
        "headActivity": "Door and Hardwares",
        "subActivity": "Misc. Door and Hardware Work",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": 0,
        "costVariancePercent": 0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 3307467,
    "totalActualCost": 0,
    "totalBalance": 3307467,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-10",
    "categoryName": "Plumbing Work",
    "items": [
      {
        "id": "orbit3-var-43",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "CP & Sanitary Fittings",
        "workStatus": "Not Completed",
        "unit": "Shop/Office",
        "budgetQty": 135.0,
        "budgetRate": 16584.6,
        "budgetCost": 2238921,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -135.0,
        "rateVariation": -16584.6,
        "balance": 2238921,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-44",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Plumbing Materials - Inside office-showroom and Vertical Lines Work (Upvc/Cpvc, PVC Pipes, Valves, Traps, Clamps, MABT, FABT, PRV, ARV, Solonide, Rack Bolts, Tafflon Tape, Whitec Cement, Canvas Pipes, Temp Motors for Dewatering, Borewell etc.)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 225000.0,
        "budgetRate": 45.0,
        "budgetCost": 10125000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 112526,
        "qtyVariation": -225000.0,
        "rateVariation": -45.0,
        "balance": 10012474,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-45",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Basement and Outer Drainage Works - Basement Storm Water Line, Below Raft Perforatted pipe, Podium-Basement Storm Water Line, Water Supply Looping Line, Outer Drainage Line Work, Planter Drain and Water Supply Line)",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 1350000.0,
        "budgetCost": 1350000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 264216,
        "qtyVariation": -1.0,
        "rateVariation": -1350000.0,
        "balance": 1085784,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-46",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Outer Plumbing Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 370000.0,
        "budgetCost": 370000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 65700,
        "qtyVariation": -1.0,
        "rateVariation": -370000.0,
        "balance": 304300,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-47",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Below Raft Perforatted pipe Material + Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 400000.0,
        "budgetCost": 400000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 357776,
        "qtyVariation": -1.0,
        "rateVariation": -400000.0,
        "balance": 42224,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-48",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "FRP ManHole Cover",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 28.0,
        "budgetRate": 10030.0,
        "budgetCost": 280840,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -28.0,
        "rateVariation": -10030.0,
        "balance": 280840,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-49",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Pnematic Pumps",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 2850000.0,
        "budgetCost": 2850000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -2850000.0,
        "balance": 2850000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-50",
        "srNo": "8",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Water Tankers",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 1100000.0,
        "budgetCost": 1100000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 213000,
        "qtyVariation": -1.0,
        "rateVariation": -1100000.0,
        "balance": 887000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-51",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Construction Water Pumping System",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 60000.0,
        "budgetCost": 60000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -60000.0,
        "balance": 60000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-52",
        "srNo": "10",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Temporary Line and Borewell Cost",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 320000.0,
        "budgetCost": 320000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -320000.0,
        "balance": 320000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-53",
        "srNo": "11",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Dewatering Cost",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 1500000.0,
        "budgetCost": 1500000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 648802,
        "qtyVariation": -1.0,
        "rateVariation": -1500000.0,
        "balance": 851198,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-54",
        "srNo": "12",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Mud Pumps",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 170000.0,
        "budgetCost": 170000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -170000.0,
        "balance": 170000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-55",
        "srNo": "13",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Plumbing Work",
        "headActivity": "Plumbing Work",
        "subActivity": "Shop/Office Labour",
        "workStatus": "Not Completed",
        "unit": "Shop/Office",
        "budgetQty": 135.0,
        "budgetRate": 21000.0,
        "budgetCost": 2835000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -135.0,
        "rateVariation": -21000.0,
        "balance": 2835000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 23599761,
    "totalActualCost": 1662020,
    "totalBalance": 21937741,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-11",
    "categoryName": "Electrical Work",
    "items": [
      {
        "id": "orbit3-var-56",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Electrical WorksOffice (Material + Labour) (Along with Passage)",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 135.0,
        "budgetRate": 58000.0,
        "budgetCost": 7830000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -135.0,
        "rateVariation": -58000.0,
        "balance": 7830000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-57",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Commom Passage & Staircase Landing Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 286.0,
        "budgetRate": 1400.0,
        "budgetCost": 400400,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -286.0,
        "rateVariation": -1400.0,
        "balance": 400400,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-58",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "D.G. Set",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 1.0,
        "budgetRate": 2250000.0,
        "budgetCost": 2250000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 3770,
        "qtyVariation": -1.0,
        "rateVariation": -2250000.0,
        "balance": 2246230,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-59",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Power Backup Pannel",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 225000.0,
        "budgetRate": 2.0,
        "budgetCost": 450000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -225000.0,
        "rateVariation": -2.0,
        "balance": 450000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-60",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Street Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 10.59,
        "budgetRate": 25960.0,
        "budgetCost": 274933,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -10.59,
        "rateVariation": -25960.0,
        "balance": 274933,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-61",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Foot Lights - Ramps/Planters",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 24.0,
        "budgetRate": 2500.0,
        "budgetCost": 60000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -24.0,
        "rateVariation": -2500.0,
        "balance": 60000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-62",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "LED Strip Light",
        "workStatus": "Not Completed",
        "unit": "Rmt",
        "budgetQty": 42.36,
        "budgetRate": 1600.0,
        "budgetCost": 67780,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -42.36,
        "rateVariation": -1600.0,
        "balance": 67780,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-63",
        "srNo": "8",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Main Entry Gate Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 5.08,
        "budgetRate": 5000.0,
        "budgetCost": 25418,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -5.08,
        "rateVariation": -5000.0,
        "balance": 25418,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-64",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Watchman Cabin Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 2.54,
        "budgetRate": 1200.0,
        "budgetCost": 3050,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2.54,
        "rateVariation": -1200.0,
        "balance": 3050,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-65",
        "srNo": "10",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Parking Lights Basement",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 195.0,
        "budgetRate": 885.0,
        "budgetCost": 172575,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -195.0,
        "rateVariation": -885.0,
        "balance": 172575,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-66",
        "srNo": "11",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Compound Wall Bracket Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 52.95,
        "budgetRate": 3000.0,
        "budgetCost": 158859,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -52.95,
        "rateVariation": -3000.0,
        "balance": 158859,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-67",
        "srNo": "12",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Spike Lights",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 25.0,
        "budgetRate": 1800.0,
        "budgetCost": 45000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -25.0,
        "rateVariation": -1800.0,
        "balance": 45000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-68",
        "srNo": "13",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Decorative Lights",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 2.0,
        "budgetRate": 75000.0,
        "budgetCost": 150000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2.0,
        "rateVariation": -75000.0,
        "balance": 150000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-69",
        "srNo": "14",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "LT Cables",
        "workStatus": "Not Completed",
        "unit": "Rmt",
        "budgetQty": 100.0,
        "budgetRate": 1950.0,
        "budgetCost": 195000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -100.0,
        "rateVariation": -1950.0,
        "balance": 195000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-70",
        "srNo": "15",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Cable Tray",
        "workStatus": "Not Completed",
        "unit": "Rmt",
        "budgetQty": 200.0,
        "budgetRate": 1200.0,
        "budgetCost": 240000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -200.0,
        "rateVariation": -1200.0,
        "balance": 240000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-71",
        "srNo": "16",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "CAT 6 Wire + Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 100000.0,
        "budgetCost": 100000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -100000.0,
        "balance": 100000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-72",
        "srNo": "17",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Misc. Electrical Works",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 522672,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -522672,
        "costVariancePercent": 0,
        "remark": "Non budgeted cost."
      },
      {
        "id": "orbit3-var-73",
        "srNo": "18",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Electrical Work",
        "headActivity": "Electrical Work",
        "subActivity": "Meter Room Works",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 350000.0,
        "budgetCost": 350000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -350000.0,
        "balance": 350000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 12773015,
    "totalActualCost": 526442,
    "totalBalance": 12769245,
    "totalVarianceAmount": -522672
  },
  {
    "id": "var-cat-12",
    "categoryName": "Fa\u00e7ade Development",
    "items": [
      {
        "id": "orbit3-var-74",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Dry cladding-Grey Colour-Tiles",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 10934.74,
        "budgetRate": 696.2,
        "budgetCost": 7612767,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -10934.74,
        "rateVariation": -696.2,
        "balance": 7612767,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-75",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Curtain Wall  (06mm Clear Glass, Mullion size 140 *55)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 19044.28,
        "budgetRate": 631.3,
        "budgetCost": 12022651,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -19044.28,
        "rateVariation": -631.3,
        "balance": 12022651,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-76",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Texture Work for Fa\u00e7ade (With colour)",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 12573.93,
        "budgetRate": 56.64,
        "budgetCost": 712187,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -12573.93,
        "rateVariation": -56.64,
        "balance": 712187,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-77",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Granite for Dry Cladding-(Material)-Ground Shop Front",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2530.93,
        "budgetRate": 631.3,
        "budgetCost": 1597775,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2530.93,
        "rateVariation": -631.3,
        "balance": 1597775,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-78",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "External Texture and colour-Red",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 45205.78,
        "budgetRate": 56.64,
        "budgetCost": 2560455,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -45205.78,
        "rateVariation": -56.64,
        "balance": 2560455,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-79",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Ground Floor Glass Front Shop",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2138.82,
        "budgetRate": 265.5,
        "budgetCost": 567857,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2138.82,
        "rateVariation": -265.5,
        "balance": 567857,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-80",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Fa\u00e7ade Development",
        "headActivity": "Fa\u00e7ade Development",
        "subActivity": "Ground Floor Glass Front Shop Door",
        "workStatus": "Not Completed",
        "unit": "nos",
        "budgetQty": 8.0,
        "budgetRate": 32000.0,
        "budgetCost": 256000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -8.0,
        "rateVariation": -32000.0,
        "balance": 256000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 25329692,
    "totalActualCost": 0,
    "totalBalance": 25329692,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-13",
    "categoryName": "Firefighting Work",
    "items": [
      {
        "id": "orbit3-var-81",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Firefighting Work",
        "headActivity": "Firefighting Work",
        "subActivity": "Firefighting Work",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 225000.0,
        "budgetRate": 35.0,
        "budgetCost": 7875000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -225000.0,
        "rateVariation": -35.0,
        "balance": 7875000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 7875000,
    "totalActualCost": 0,
    "totalBalance": 7875000,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-14",
    "categoryName": "Signages",
    "items": [],
    "totalBudgetCost": 0,
    "totalActualCost": 0,
    "totalBalance": 0,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-15",
    "categoryName": "Elevators",
    "items": [
      {
        "id": "orbit3-var-82",
        "srNo": "1",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "Elevators",
        "headActivity": "Elevators",
        "subActivity": "Elevators",
        "workStatus": "Not Completed",
        "unit": "Nos",
        "budgetQty": 3.0,
        "budgetRate": 2050000.0,
        "budgetCost": 6150000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 553201,
        "qtyVariation": -3.0,
        "rateVariation": -2050000.0,
        "balance": 5596799,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 6150000,
    "totalActualCost": 553201,
    "totalBalance": 5596799,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-16",
    "categoryName": "Glass, Railing, and Louvers Installation",
    "items": [
      {
        "id": "orbit3-var-83",
        "srNo": "1",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Aluminum Window Section-Office",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2430.89,
        "budgetRate": 375.0,
        "budgetCost": 911583,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2430.89,
        "rateVariation": -375.0,
        "balance": 911583,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-84",
        "srNo": "2",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Aluminum Louvers-External Elevation",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 3899.8,
        "budgetRate": 177.0,
        "budgetCost": 690264,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -3899.8,
        "rateVariation": -177.0,
        "balance": 690264,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-85",
        "srNo": "3",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Aluminum Ventialtion-Toilet",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 507.63,
        "budgetRate": 324.5,
        "budgetCost": 164726,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -507.63,
        "rateVariation": -324.5,
        "balance": 164726,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-86",
        "srNo": "4",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Projection Aluminum Fabrication",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 3611.92,
        "budgetRate": 177.0,
        "budgetCost": 639311,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -3611.92,
        "rateVariation": -177.0,
        "balance": 639311,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-87",
        "srNo": "5",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Glass Railing-External Balcony",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2640.95,
        "budgetRate": 531.0,
        "budgetCost": 1402346,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2640.95,
        "rateVariation": -531.0,
        "balance": 1402346,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-88",
        "srNo": "6",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Atrium MS/GI Railing",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2195.86,
        "budgetRate": 236.0,
        "budgetCost": 518222,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2195.86,
        "rateVariation": -236.0,
        "balance": 518222,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-89",
        "srNo": "7",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Electric Duct-Aluminum. Fabrication",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 3516.77,
        "budgetRate": 531.0,
        "budgetCost": 1867405,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -3516.77,
        "rateVariation": -531.0,
        "balance": 1867405,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-90",
        "srNo": "8",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Staircase Passage Side-Window",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2109.17,
        "budgetRate": 375.0,
        "budgetCost": 790938,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2109.17,
        "rateVariation": -375.0,
        "balance": 790938,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-91",
        "srNo": "9",
        "parentGroup": "Architectural and MEP Finishing Works",
        "subGroup": "Glass, Railing, and Louvers Installation",
        "headActivity": "Glass, Railing, and Louvers Installation",
        "subActivity": "Fabrication Work (Canopy and Staircase Railing)",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 2500000.0,
        "budgetCost": 2500000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -2500000.0,
        "balance": 2500000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 9484795,
    "totalActualCost": 0,
    "totalBalance": 9484795,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-17",
    "categoryName": "External Site Development",
    "items": [
      {
        "id": "orbit3-var-92",
        "srNo": "1",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Drive Way-Trimix",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 8525.09,
        "budgetRate": 194.7,
        "budgetCost": 1659835,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -8525.09,
        "rateVariation": -194.7,
        "balance": 1659835,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-93",
        "srNo": "2",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Ground Shop Front Otta-Stone Flooring",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 3605.94,
        "budgetRate": 185.26,
        "budgetCost": 668036,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -3605.94,
        "rateVariation": -185.26,
        "balance": 668036,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-94",
        "srNo": "3",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Compound Wall-(Civil+Finishing Work)",
        "workStatus": "Not Completed",
        "unit": "Rft",
        "budgetQty": 432.96,
        "budgetRate": 6200.0,
        "budgetCost": 2684352,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -432.96,
        "rateVariation": -6200.0,
        "balance": 2684352,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-95",
        "srNo": "4",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Ground Shop Front Area Parking way",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 2131.16,
        "budgetRate": 159.3,
        "budgetCost": 339494,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -2131.16,
        "rateVariation": -159.3,
        "balance": 339494,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      },
      {
        "id": "orbit3-var-96",
        "srNo": "5",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Depart Labour",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 0,
        "budgetRate": 0,
        "budgetCost": 0,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 1162454,
        "qtyVariation": 0,
        "rateVariation": 0,
        "balance": 0,
        "costVarianceAmount": -1162454,
        "costVariancePercent": 0,
        "remark": "Non budgeted cost."
      },
      {
        "id": "orbit3-var-97",
        "srNo": "6",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "External Site Development",
        "headActivity": "External Site Development",
        "subActivity": "Transformer Space",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 753.48,
        "budgetRate": 2950.0,
        "budgetCost": 2222766,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -753.48,
        "rateVariation": -2950.0,
        "balance": 2222766,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 7574483,
    "totalActualCost": 1162454,
    "totalBalance": 7574483,
    "totalVarianceAmount": -1162454
  },
  {
    "id": "var-cat-18",
    "categoryName": "Mechanical Parking",
    "items": [
      {
        "id": "orbit3-var-98",
        "srNo": "1",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "Mechanical Parking",
        "headActivity": "Mechanical Parking",
        "subActivity": "Mechanical Parking",
        "workStatus": "Not Completed",
        "unit": "Nos.",
        "budgetQty": 59.0,
        "budgetRate": 277300.0,
        "budgetCost": 16360700,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -59.0,
        "rateVariation": -277300.0,
        "balance": 16360700,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 16360700,
    "totalActualCost": 0,
    "totalBalance": 16360700,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-19",
    "categoryName": "Basement Exhaust and Ventilation System",
    "items": [
      {
        "id": "orbit3-var-99",
        "srNo": "1",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "Basement Exhaust and Ventilation System",
        "headActivity": "Basement Exhaust and Ventilation System",
        "subActivity": "Basement Exhaust and Ventilation System",
        "workStatus": "Not Completed",
        "unit": "LS",
        "budgetQty": 1.0,
        "budgetRate": 2000000.0,
        "budgetCost": 2000000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -1.0,
        "rateVariation": -2000000.0,
        "balance": 2000000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 2000000,
    "totalActualCost": 0,
    "totalBalance": 2000000,
    "totalVarianceAmount": 0
  },
  {
    "id": "var-cat-20",
    "categoryName": "Foyer Development",
    "items": [
      {
        "id": "orbit3-var-100",
        "srNo": "1",
        "parentGroup": "Building Services, Utility & C.O.P Area work",
        "subGroup": "Foyer Development",
        "headActivity": "Foyer Development",
        "subActivity": "Foyer Development",
        "workStatus": "Not Completed",
        "unit": "Sqft",
        "budgetQty": 650.0,
        "budgetRate": 3500.0,
        "budgetCost": 2275000,
        "poQty": 0,
        "poRate": 0,
        "poAmount": 0,
        "actualBillQty": 0,
        "actualBillRate": 0,
        "actualTotalCost": 0,
        "qtyVariation": -650.0,
        "rateVariation": -3500.0,
        "balance": 2275000,
        "costVarianceAmount": 0,
        "costVariancePercent": 0.0,
        "remark": ""
      }
    ],
    "totalBudgetCost": 2275000,
    "totalActualCost": 0,
    "totalBalance": 2275000,
    "totalVarianceAmount": 0
  }
];
